Repository prathimacode-hub/Awesome_Python_Scripts, pull requests merged in 2021-08, with the labels that each got.

#903 Hand Cricket
  BasicPythonScripts/Hand Cricket/Hand_Cricket.py
  BasicPythonScripts/Hand Cricket/Images/Hand Cricket.jpg
  BasicPythonScripts/Hand Cricket/README.md
  BasicPythonScripts/Hand Cricket/requirements.txt
Labels: DCP21, To Do, 🟨 Level2

#905 Added Random Shape Image Generator in GUI Scripts
  GUIScripts/Random Shape Image Generator/Images/1.jpg
  GUIScripts/Random Shape Image Generator/Images/2.jpg
  GUIScripts/Random Shape Image Generator/Images/3.jpg
  GUIScripts/Random Shape Image Generator/Images/4.jpg
  GUIScripts/Random Shape Image Generator/Images/5.jpg
  GUIScripts/Random Shape Image Generator/Images/6.jpg
  GUIScripts/Random Shape Image Generator/README.md
  GUIScripts/Random Shape Image Generator/random_shape_image_generator.py
  GUIScripts/Random Shape Image Generator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#908 Added American and British English Conversion in GUIScripts
  GUIScripts/American and British English Conversion/Images/1.jpg
  GUIScripts/American and British English Conversion/Images/2.jpg
  GUIScripts/American and British English Conversion/Images/3.jpg
  GUIScripts/American and British English Conversion/Images/4.jpg
  GUIScripts/American and British English Conversion/Images/5.jpg
  GUIScripts/American and British English Conversion/Images/6.jpg
  GUIScripts/American and British English Conversion/Images/7.jpg
  GUIScripts/American and British English Conversion/Images/8.jpg
  GUIScripts/American and British English Conversion/Images/cheatsheet.jpg
  GUIScripts/American and British English Conversion/Images/front.jpg
  GUIScripts/American and British English Conversion/README.md
  GUIScripts/American and British English Conversion/american_and_british_english_conversion.py
  GUIScripts/American and British English Conversion/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#912 Dr Battery
  GUIScripts/Dr Battery/Dr_Battery.py
  GUIScripts/Dr Battery/Images/Full Charge.jpg
  GUIScripts/Dr Battery/Images/LowBattery.jpg
  GUIScripts/Dr Battery/Images/Over Charged.jpg
  GUIScripts/Dr Battery/README.md
  GUIScripts/Dr Battery/requirements.txt
Labels: DCP21, To Do, 🟩 Level1

#914 Added Adding Frames to Video in GUIScripts
  GUIScripts/Adding Frames to Video/Images/1.jpg
  GUIScripts/Adding Frames to Video/Images/10.jpg
  GUIScripts/Adding Frames to Video/Images/11.jpg
  GUIScripts/Adding Frames to Video/Images/12.jpg
  GUIScripts/Adding Frames to Video/Images/2.jpg
  GUIScripts/Adding Frames to Video/Images/3.jpg
  GUIScripts/Adding Frames to Video/Images/4.jpg
  GUIScripts/Adding Frames to Video/Images/5.jpg
  GUIScripts/Adding Frames to Video/Images/6.jpg
  GUIScripts/Adding Frames to Video/Images/7.jpg
  GUIScripts/Adding Frames to Video/Images/8.jpg
  GUIScripts/Adding Frames to Video/Images/9.jpg
  GUIScripts/Adding Frames to Video/Images/front.jpg
  GUIScripts/Adding Frames to Video/README.md
  GUIScripts/Adding Frames to Video/adding_frames_to_video.py
  GUIScripts/Adding Frames to Video/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#893 Added Code to Detect Lane from Image
  ImageProcessingScripts/Image Lane Detector/Images/Detected_Lane.jpg
  ImageProcessingScripts/Image Lane Detector/Images/road.jpg
  ImageProcessingScripts/Image Lane Detector/README.md
  ImageProcessingScripts/Image Lane Detector/lane_detector.py
  ImageProcessingScripts/Image Lane Detector/requirements.txt
Labels: DCP21, To Do, 🟨 Level2

#917 Enhanced Video Player with Progress bar in GUIScripts
  GUIScripts/Video Player/Images/2.jpg
  GUIScripts/Video Player/Images/3.jpg
  GUIScripts/Video Player/Images/4.jpg
  GUIScripts/Video Player/Images/5.jpg
  GUIScripts/Video Player/Images/6.jpg
  GUIScripts/Video Player/Images/7.jpg
  GUIScripts/Video Player/Images/8.jpg
  GUIScripts/Video Player/Images/9.jpg
  GUIScripts/Video Player/README_enhanced.md
  GUIScripts/Video Player/requirements.txt
  GUIScripts/Video Player/video_player.py
Labels: LGMSOC21, To Do, 🟨 Level2

#916 Added OTP Generator Script
  BasicPythonScripts/OTP Generator/Images/image1.PNG
  BasicPythonScripts/OTP Generator/Images/image2.PNG
  BasicPythonScripts/OTP Generator/Images/image3.PNG
  BasicPythonScripts/OTP Generator/README.md
  BasicPythonScripts/OTP Generator/otp_generator.py
  BasicPythonScripts/OTP Generator/requirements.txt
Labels: DCP21, 🟪 Level0

#919 Wiki Bot
  AutomationScripts/Wiki Bot/Media/Images/Wiki_Bot Output_1.png
  AutomationScripts/Wiki Bot/Media/Images/Wiki_Bot Output_2.png
  AutomationScripts/Wiki Bot/Media/Videos/Wiki_Bot Output_1.mp4
  AutomationScripts/Wiki Bot/Media/Videos/Wiki_Bot_Output_2.mp4
  AutomationScripts/Wiki Bot/README.md
  AutomationScripts/Wiki Bot/Wiki_Bot.py
  AutomationScripts/Wiki Bot/requirements.txt
Labels: DCP21, To Do, 🟩 Level1

#965 Added Large Image Preview in GUIScripts
  GUIScripts/Large Image Preview/Images/1.jpg
  GUIScripts/Large Image Preview/Images/2.jpg
  GUIScripts/Large Image Preview/Images/3.jpg
  GUIScripts/Large Image Preview/Images/4.jpg
  GUIScripts/Large Image Preview/Images/5.jpg
  GUIScripts/Large Image Preview/Images/6.jpg
  GUIScripts/Large Image Preview/Images/7.jpg
  GUIScripts/Large Image Preview/Images/8.jpg
  GUIScripts/Large Image Preview/Images/9.jpg
  GUIScripts/Large Image Preview/README.md
  GUIScripts/Large Image Preview/large_image_preview.py
  GUIScripts/Large Image Preview/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#910 Voice Recorder using Python
  BasicPythonScripts/Voice Recorder/Images/voice_recorder0.png
  BasicPythonScripts/Voice Recorder/Images/voice_recorder1.png
  BasicPythonScripts/Voice Recorder/README.md
  BasicPythonScripts/Voice Recorder/Recording Sample/recording7712.wav
  BasicPythonScripts/Voice Recorder/requirements.txt
  BasicPythonScripts/Voice Recorder/voice_recorder.py
Labels: LGMSOC21, 🟩 Level1, To Do

#970 Added Instagram Profile Downloader in Automation Scripts
  AutomationScripts/Instagram Profile Downloader/Images/1.jpg
  AutomationScripts/Instagram Profile Downloader/Images/10.jpg
  AutomationScripts/Instagram Profile Downloader/Images/11.jpg
  AutomationScripts/Instagram Profile Downloader/Images/2.jpg
  AutomationScripts/Instagram Profile Downloader/Images/3.jpg
  AutomationScripts/Instagram Profile Downloader/Images/4.jpg
  AutomationScripts/Instagram Profile Downloader/Images/5.jpg
  AutomationScripts/Instagram Profile Downloader/Images/6.jpg
  AutomationScripts/Instagram Profile Downloader/Images/7.jpg
  AutomationScripts/Instagram Profile Downloader/Images/8.jpg
  AutomationScripts/Instagram Profile Downloader/Images/9.jpg
  AutomationScripts/Instagram Profile Downloader/Images/front.png
  AutomationScripts/Instagram Profile Downloader/README.md
  AutomationScripts/Instagram Profile Downloader/instagram_profile_downloader.py
  AutomationScripts/Instagram Profile Downloader/requirements.txt
Labels: 🟨 Level2, LGMSOC21, To Do

#974 Added Pomodoro Timer in GUIScripts
  GUIScripts/Pomodoro Timer/Images/1.jpg
  GUIScripts/Pomodoro Timer/Images/2.jpg
  GUIScripts/Pomodoro Timer/Images/3.jpg
  GUIScripts/Pomodoro Timer/Images/4.jpg
  GUIScripts/Pomodoro Timer/Images/5.jpg
  GUIScripts/Pomodoro Timer/Images/6.jpg
  GUIScripts/Pomodoro Timer/Images/7.jpg
  GUIScripts/Pomodoro Timer/Images/8.jpg
  GUIScripts/Pomodoro Timer/Images/9.jpg
  GUIScripts/Pomodoro Timer/Images/front.jpg
  GUIScripts/Pomodoro Timer/README.md
  GUIScripts/Pomodoro Timer/promodoro_timer.py
  GUIScripts/Pomodoro Timer/requirements.txt
Labels: 🟨 Level2, LGMSOC21, To Do

#972 Added Morse Code Translator in GUIScripts
  GUIScripts/Morse Code Translator/Images/1.jpg
  GUIScripts/Morse Code Translator/Images/2.jpg
  GUIScripts/Morse Code Translator/Images/3.jpg
  GUIScripts/Morse Code Translator/Images/4.jpg
  GUIScripts/Morse Code Translator/Images/5.jpg
  GUIScripts/Morse Code Translator/Images/6.jpg
  GUIScripts/Morse Code Translator/Images/7.jpg
  GUIScripts/Morse Code Translator/Images/8.jpg
  GUIScripts/Morse Code Translator/Images/cheatsheet.jpg
  GUIScripts/Morse Code Translator/Images/front.jpg
  GUIScripts/Morse Code Translator/README.md
  GUIScripts/Morse Code Translator/morse_code_translator.py
  GUIScripts/Morse Code Translator/requirements.txt
Labels: 🟨 Level2, LGMSOC21, To Do

#971 Added Connect Four to PyGame Scripts
  PyGamesScripts/Connect Four/Images/Screenshot (370).png
  PyGamesScripts/Connect Four/README.md
  PyGamesScripts/Connect Four/connect_four.py
  PyGamesScripts/Connect Four/requirements.txt
Labels: 🟨 Level2, To Do, DCP21

#975 Added Website Status Checker in GUIScripts
  GUIScripts/Website Status Checker/Images/1.jpg
  GUIScripts/Website Status Checker/Images/10.jpg
  GUIScripts/Website Status Checker/Images/11.jpg
  GUIScripts/Website Status Checker/Images/2.jpg
  GUIScripts/Website Status Checker/Images/3.jpg
  GUIScripts/Website Status Checker/Images/4.jpg
  GUIScripts/Website Status Checker/Images/5.jpg
  GUIScripts/Website Status Checker/Images/6.jpg
  GUIScripts/Website Status Checker/Images/7.jpg
  GUIScripts/Website Status Checker/Images/8.jpg
  GUIScripts/Website Status Checker/Images/9.jpg
  GUIScripts/Website Status Checker/Images/front.jpg
  GUIScripts/Website Status Checker/README.md
  GUIScripts/Website Status Checker/requirements.txt
  GUIScripts/Website Status Checker/website_status_checker.py
Labels: 🟨 Level2, LGMSOC21, To Do

#977 html mail sender
  GUIScripts/HTML Mail Sender/Images/img.PNG
  GUIScripts/HTML Mail Sender/README.md
  GUIScripts/HTML Mail Sender/app.py
  GUIScripts/HTML Mail Sender/requirements.txt
  GUIScripts/HTML Mail Sender/static/main.css
  GUIScripts/HTML Mail Sender/templates/home.html
Labels: 🟨 Level2, To Do, DCP21

#979 Added Network Usage Tracker in GUIScripts
  GUIScripts/Network Usage Tracker/Images/1.jpg
  GUIScripts/Network Usage Tracker/Images/2.jpg
  GUIScripts/Network Usage Tracker/Images/3.jpg
  GUIScripts/Network Usage Tracker/Images/4.jpg
  GUIScripts/Network Usage Tracker/Images/5.jpg
  GUIScripts/Network Usage Tracker/Images/6.jpg
  GUIScripts/Network Usage Tracker/Images/7.jpg
  GUIScripts/Network Usage Tracker/Images/8.jpg
  GUIScripts/Network Usage Tracker/Images/front.png
  GUIScripts/Network Usage Tracker/README.md
  GUIScripts/Network Usage Tracker/network_usage_tracker.py
  GUIScripts/Network Usage Tracker/requirements.txt
Labels: 🟨 Level2, LGMSOC21, To Do

#896 Internship - Internshala
  WebScrapingScripts/Internship-Internshala/Images/Internshala logo.jpg
  WebScrapingScripts/Internship-Internshala/Images/Screenshot 1.png
  WebScrapingScripts/Internship-Internshala/Images/Screenshot 2.png
  WebScrapingScripts/Internship-Internshala/README.md
  WebScrapingScripts/Internship-Internshala/export_to_excel.py
  WebScrapingScripts/Internship-Internshala/get_parameters.py
  WebScrapingScripts/Internship-Internshala/get_url_params.py
  WebScrapingScripts/Internship-Internshala/internship_internshala.py
  WebScrapingScripts/Internship-Internshala/requirements.txt
Labels: 🟧 Level3, LGMSOC21, To Do

#984 Lyrics Downloader
  APIScripts/Lyrics API/Images/Screenshot/ss.png
  APIScripts/Lyrics API/Lyrics/lyrics.txt
  APIScripts/Lyrics API/README.md
  APIScripts/Lyrics API/lyrics.py
  APIScripts/Lyrics API/requirements.txt
Labels: LGMSOC21, 🟩 Level1, To Do
