Repository prathimacode-hub/Awesome_Python_Scripts, pull requests merged in 2021-06, with the labels that each got.

#88 Typing Speed Test
  BasicPythonScripts/Typing Speed Test/Images/README.md
  BasicPythonScripts/Typing Speed Test/Images/Result_1.png
  BasicPythonScripts/Typing Speed Test/Images/Result_2.png
  BasicPythonScripts/Typing Speed Test/README.md
  BasicPythonScripts/Typing Speed Test/requirements.txt
  BasicPythonScripts/Typing Speed Test/typing_speed_test.py
Labels: LGMSOC21, 🟨 Level2

#89 Alarm Clock Program
  BasicPythonScripts/Alarm Clock/Images/Screenshot.png
  BasicPythonScripts/Alarm Clock/README.md
  BasicPythonScripts/Alarm Clock/alarm_clock.py
  BasicPythonScripts/Alarm Clock/requirements.txt
  BasicPythonScripts/Alarm_clock/ReadMe.md
  BasicPythonScripts/Alarm_clock/Screenshot.png
  BasicPythonScripts/Alarm_clock/alarm_clock.py
  BasicPythonScripts/Alarm_clock/requirement.md
Labels: LGMSOC21, 🟨 Level2

#103 added Flappy Bird game
  PyGamesScripts/Flappy Bird/Images/background.png
  PyGamesScripts/Flappy Bird/Images/bird.gif
  PyGamesScripts/Flappy Bird/Images/bird_wing_down.png
  PyGamesScripts/Flappy Bird/Images/bird_wing_up.png
  PyGamesScripts/Flappy Bird/Images/ground.png
  PyGamesScripts/Flappy Bird/Images/output.png
  PyGamesScripts/Flappy Bird/Images/pipe.png
  PyGamesScripts/Flappy Bird/Images/pipe_body.png
  PyGamesScripts/Flappy Bird/Images/pipe_end.png
  PyGamesScripts/Flappy Bird/README.md
  PyGamesScripts/Flappy Bird/flappy_bird.py
Labels: LGMSOC21, 🟨 Level2

#73 Image Steganography
  ImageProcessingScripts/.DS_Store
  ImageProcessingScripts/Image Steganography/.DS_Store
  ImageProcessingScripts/Image Steganography/Images/.DS_Store
  ImageProcessingScripts/Image Steganography/Images/decoding_ss.png
  ImageProcessingScripts/Image Steganography/Images/encoding_ss.png
  ImageProcessingScripts/Image Steganography/Images/output.png
  ImageProcessingScripts/Image Steganography/Images/test.png
  ImageProcessingScripts/Image Steganography/README.md
  ImageProcessingScripts/Image Steganography/image_steganography.py
Labels: LGMSOC21, 🟨 Level2

#104 Issue 70: Added python text translator
  GUIScripts/Text Translator/Images/demo0.PNG
  GUIScripts/Text Translator/Images/demo1.PNG
  GUIScripts/Text Translator/Images/demo2.png
  GUIScripts/Text Translator/Images/demo3.PNG
  GUIScripts/Text Translator/README.md
  GUIScripts/Text Translator/requirements.txt
  GUIScripts/Text Translator/text_translator.py
Labels: LGMSOC21, 🟨 Level2

#87 Added Twitter API
  APIScripts/Twitter API/Images/covid_csv.png
  APIScripts/Twitter API/README.md
  APIScripts/Twitter API/twitter_api.py
Labels: LGMSOC21, 🟨 Level2

#112 Text Image to Handwritten Text Image Converter
  ImageProcessingScripts/README.md
  ImageProcessingScripts/Text to HandWritten/Images/Converted_Image.png
  ImageProcessingScripts/Text to HandWritten/Images/Text.png
  ImageProcessingScripts/Text to HandWritten/README.md
  ImageProcessingScripts/Text to HandWritten/text_to_handwritten_text.py
Labels: LGMSOC21, 🟨 Level2

#124 What's Your Story?
  BasicPythonScripts/What's Your Story/Images/screenshot1.png
  BasicPythonScripts/What's Your Story/Images/screenshot2.png
  BasicPythonScripts/What's Your Story/Images/screenshot3.png
  BasicPythonScripts/What's Your Story/README.md
  BasicPythonScripts/What's Your Story/what's_your_story.py
Labels: LGMSOC21, 🟨 Level2

#125 Added Guess The Number
  PyGamesScripts/Guess The Number/Images/guessnum.PNG
  PyGamesScripts/Guess The Number/README.md
  PyGamesScripts/Guess The Number/guess_the_number.py
  PyGamesScripts/README.md
Labels: LGMSOC21, 🟨 Level2

#135 Movie API Script added
  APIScripts/OMDB API/Images/img1.PNG
  APIScripts/OMDB API/Images/img2.PNG
  APIScripts/OMDB API/Images/img3.PNG
  APIScripts/OMDB API/Images/img4.PNG
  APIScripts/OMDB API/README.md
  APIScripts/OMDB API/omdb_api.py
Labels: 🟨 Level2

#133 Plagiarism Checker
  BasicPythonScripts/Plagiarism Checker/Images/Demo Output.png
  BasicPythonScripts/Plagiarism Checker/README.md
  BasicPythonScripts/Plagiarism Checker/Text Files/file1.txt
  BasicPythonScripts/Plagiarism Checker/Text Files/file2.txt
  BasicPythonScripts/Plagiarism Checker/plagiarism_checker.py
Labels: 🟨 Level2

#139 ATM Machine System
  BasicPythonScripts/ATM Machine System/Images/README.md
  BasicPythonScripts/ATM Machine System/Images/output_1(atm).png
  BasicPythonScripts/ATM Machine System/Images/output_2(atm).png
  BasicPythonScripts/ATM Machine System/README.md
  BasicPythonScripts/ATM Machine System/atm_machine_system.py
  BasicPythonScripts/ATM Machine System/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#136 Hangman
  PyGamesScripts/Hangman/Images/categories.PNG
  PyGamesScripts/Hangman/Images/guessing1.PNG
  PyGamesScripts/Hangman/Images/guessing2.PNG
  PyGamesScripts/Hangman/Images/guessing3.PNG
  PyGamesScripts/Hangman/Images/guessing4.PNG
  PyGamesScripts/Hangman/Images/hangman.PNG
  PyGamesScripts/Hangman/Images/loosing.PNG
  PyGamesScripts/Hangman/Images/playingAgain.PNG
  PyGamesScripts/Hangman/Images/winning.PNG
  PyGamesScripts/Hangman/README.md
  PyGamesScripts/Hangman/hangman.py
Labels: LGMSOC21, 🟧 Level3

#137 Added Phone Number Info
  BasicPythonScripts/Phone Number Info/Images/phn1.PNG
  BasicPythonScripts/Phone Number Info/Images/phn2.PNG
  BasicPythonScripts/Phone Number Info/README.md
  BasicPythonScripts/Phone Number Info/phone_number_info.py
  BasicPythonScripts/Phone Number Info/requirements.txt
  BasicPythonScripts/README.md
Labels: LGMSOC21, 🟨 Level2

#144 Issue 111: Added Image Blending Script
  ImageProcessingScripts/Image Blending/Images/apple.jpg
  ImageProcessingScripts/Image Blending/Images/demo1.PNG
  ImageProcessingScripts/Image Blending/Images/demo2.PNG
  ImageProcessingScripts/Image Blending/Images/demo3.PNG
  ImageProcessingScripts/Image Blending/Images/fish.jpg
  ImageProcessingScripts/Image Blending/Images/orange.jpg
  ImageProcessingScripts/Image Blending/Images/original_img.PNG
  ImageProcessingScripts/Image Blending/Images/original_img2.PNG
  ImageProcessingScripts/Image Blending/Images/original_img3.PNG
  ImageProcessingScripts/Image Blending/Images/pears.jpg
  ImageProcessingScripts/Image Blending/Images/under_water.jpg
  ImageProcessingScripts/Image Blending/README.md
  ImageProcessingScripts/Image Blending/image_blending.py
  ImageProcessingScripts/Image Blending/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#150 Added links to the badges in README.md file
  README.md
Labels: LGMSOC21, 🟩 Level1

#148 Password Checker
  APIScripts/Password Checker/Images/Output.png
  APIScripts/Password Checker/README.md
  APIScripts/Password Checker/password_checker.py
  APIScripts/Password Checker/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#153 Brick Breaker Game
  PyGamesScripts/Brick Breaker Game/Images/img.png
  PyGamesScripts/Brick Breaker Game/README.md
  PyGamesScripts/Brick Breaker Game/brick_breaker.py
Labels: LGMSOC21, 🟧 Level3

#132 PDF to Audiobook converter
  BasicPythonScripts/PDF to Audiobook Converter/Images/code.PNG
  BasicPythonScripts/PDF to Audiobook Converter/Images/running.PNG
  BasicPythonScripts/PDF to Audiobook Converter/README.md
  BasicPythonScripts/PDF to Audiobook Converter/Related/sample.pdf
  BasicPythonScripts/PDF to Audiobook Converter/pdf_to_audiobook_converter.py
  BasicPythonScripts/PDF to Audiobook Converter/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#143 Added Card_game
  PyGamesScripts/Card Game/Images/Screenshot.png
  PyGamesScripts/Card Game/README.md
  PyGamesScripts/Card Game/card_game.py
Labels: LGMSOC21, 🟧 Level3

#142 Facebook Messenger Automation
  AutomationScripts/Facebook Messenger Automation/Images/README.md
  AutomationScripts/Facebook Messenger Automation/Images/output(facebook messenger).png
  AutomationScripts/Facebook Messenger Automation/Images/output(facebook).png
  AutomationScripts/Facebook Messenger Automation/README.md
  AutomationScripts/Facebook Messenger Automation/facebook_messenger_automation.py
  AutomationScripts/Facebook Messenger Automation/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#163 Weather Notifier Script
  AutomationScripts/README.md
  AutomationScripts/Weather Notifier/Images/Screenshot.jpg
  AutomationScripts/Weather Notifier/README.md
  AutomationScripts/Weather Notifier/requirements.txt
  AutomationScripts/Weather Notifier/weather_notifier.py
Labels: LGMSOC21, 🟨 Level2

#164 QR Code Scanner Web Application
  GUIScripts/QR Code Scanner/Images/Final.gif
  GUIScripts/QR Code Scanner/Images/LGM.png
  GUIScripts/QR Code Scanner/README.md
  GUIScripts/QR Code Scanner/qr_code_scan.py
  GUIScripts/QR Code Scanner/requirements.txt"
Labels: LGMSOC21, 🟨 Level2

#162 Added script for Jokes
  AutomationScripts/Jokes Automation/Images/img0.png
  AutomationScripts/Jokes Automation/Images/img1.png
  AutomationScripts/Jokes Automation/Images/img2.png
  AutomationScripts/Jokes Automation/Images/img3.png
  AutomationScripts/Jokes Automation/Images/img4.png
  AutomationScripts/Jokes Automation/README.md
  AutomationScripts/Jokes Automation/jokes_automation.py
Labels: LGMSOC21, 🟧 Level3

#168 Grammar Correction
  AutomationScripts/Grammar Correction/Images/README.md
  AutomationScripts/Grammar Correction/Images/output_1(grammar).png
  AutomationScripts/Grammar Correction/Images/output_2(grammar).png
  AutomationScripts/Grammar Correction/README.md
  AutomationScripts/Grammar Correction/grammar_correction.py
  AutomationScripts/Grammar Correction/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#172 Current Stock Price
  WebScrapingScripts/Current Stock Price/Images/currstock.PNG
  WebScrapingScripts/Current Stock Price/README.md
  WebScrapingScripts/Current Stock Price/current_stock_price.py
  WebScrapingScripts/Current Stock Price/requirements.txt
  WebScrapingScripts/README.md
Labels: LGMSOC21, 🟨 Level2

#169 My Routine Database System
  GUIScripts/My Routine Database System/Images/Search.PNG
  GUIScripts/My Routine Database System/Images/view_all.PNG
  GUIScripts/My Routine Database System/README.md
  GUIScripts/My Routine Database System/my_routine_database_system.py
  GUIScripts/My Routine Database System/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#174 PC_Cleaner
  BasicPythonScripts/PC Cleaner/Images/output_1.jpg
  BasicPythonScripts/PC Cleaner/Images/output_2.jpg
  BasicPythonScripts/PC Cleaner/README.md
  BasicPythonScripts/PC Cleaner/pc_cleaner.py
  BasicPythonScripts/PC Cleaner/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#167 Real-Time Bitcoin Rate
  WebScrapingScripts/Real-Time Bitcoin Rate/Images/Demo Output.png
  WebScrapingScripts/Real-Time Bitcoin Rate/README.md
  WebScrapingScripts/Real-Time Bitcoin Rate/bitcoin_rate.py
  WebScrapingScripts/Real-Time Bitcoin Rate/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#175 Jumbled Words Guessing Game
  PyGamesScripts/Jumbled Words Guessing Game/Images/answer.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/categories page.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/exit.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/gamepage.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/guessing.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/intropage.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/nextword.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/right ans.PNG
  PyGamesScripts/Jumbled Words Guessing Game/Images/wrong ans.PNG
  PyGamesScripts/Jumbled Words Guessing Game/README.md
  PyGamesScripts/Jumbled Words Guessing Game/jumbled_words.py
  PyGamesScripts/Jumbled Words Guessing Game/requirements.txt
  PyGamesScripts/jumbled-words-guessing-game/Images/answer.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/categories page.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/exit.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/gamepage.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/guessing.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/intropage.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/nextword.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/right ans.PNG
  PyGamesScripts/jumbled-words-guessing-game/Images/wrong ans.PNG
Labels: LGMSOC21, 🟧 Level3

#192 Matchmaker Game
  PyGamesScripts/Matchmaker Game/Images/README.md
  PyGamesScripts/Matchmaker Game/Images/output(matchmaker_ending).png
  PyGamesScripts/Matchmaker Game/Images/output(matchmaker_going).png
  PyGamesScripts/Matchmaker Game/Images/output(matchmaker_starting).png
  PyGamesScripts/Matchmaker Game/README.md
  PyGamesScripts/Matchmaker Game/matchmaker_game.py
  PyGamesScripts/Matchmaker Game/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#189 Added sudoku game
  PyGamesScripts/Sudoku/Images/sudoku.jpeg
  PyGamesScripts/Sudoku/README.md
  PyGamesScripts/Sudoku/app_class.py
  PyGamesScripts/Sudoku/buttonClass.py
  PyGamesScripts/Sudoku/main.py
  PyGamesScripts/Sudoku/requirements.txt
  PyGamesScripts/Sudoku/settings.py
Labels: LGMSOC21, 🟧 Level3

#188 Distance Finder
  BasicPythonScripts/Distance Finder/Images/output.jpg
  BasicPythonScripts/Distance Finder/README.md
  BasicPythonScripts/Distance Finder/distance.py
  BasicPythonScripts/Distance Finder/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#196 Shut Down PC using Voice
  AutomationScripts/Shut Down PC/Images/output.png
  AutomationScripts/Shut Down PC/README.md
  AutomationScripts/Shut Down PC/requirements.txt
  AutomationScripts/Shut Down PC/shutdown_pc.py
Labels: LGMSOC21, 🟨 Level2

#184 Random email
  AutomationScripts/Random Email Generator/Images/RandomEmail.png
  AutomationScripts/Random Email Generator/README.md
  AutomationScripts/Random Email Generator/random_email_generator.py
  AutomationScripts/Random Email Generator/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#195 Added Bubble Checker Game in PyGames Scripts
  PyGamesScripts/Bubble Catcher Game/README.md
  PyGamesScripts/Bubble Catcher Game/bubble_catcher.py
  PyGamesScripts/Bubble Catcher Game/images/1.jpg
  PyGamesScripts/Bubble Catcher Game/images/2.jpg
  PyGamesScripts/Bubble Catcher Game/images/3.jpg
  PyGamesScripts/Bubble Catcher Game/images/4.jpg
  PyGamesScripts/Bubble Catcher Game/images/bgimage.jpg
  PyGamesScripts/Bubble Catcher Game/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#201 Real-Time Petrol Price
  WebScrapingScripts/Real-Time Petrol Price/Images/Demo Output.png
  WebScrapingScripts/Real-Time Petrol Price/README.md
  WebScrapingScripts/Real-Time Petrol Price/petrol_price.py
  WebScrapingScripts/Real-Time Petrol Price/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#202 Qrcode Generator
  AutomationScripts/Qrcode Generator/Images/README.md
  AutomationScripts/Qrcode Generator/Images/output(qr).png
  AutomationScripts/Qrcode Generator/README.md
  AutomationScripts/Qrcode Generator/qrcode_generator.py
  AutomationScripts/Qrcode Generator/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#208 Image to ASCII Converter
  ImageProcessingScripts/Image to ASCII Art/Images/input.png
  ImageProcessingScripts/Image to ASCII Art/Images/output.png
  ImageProcessingScripts/Image to ASCII Art/README.md
  ImageProcessingScripts/Image to ASCII Art/image_to_ascii.py
  ImageProcessingScripts/Image to ASCII Art/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#158 Added Bitcoin Mining Script
  AutomationScripts/BitCoin Mining/Images/Sample.png
  AutomationScripts/BitCoin Mining/README.md
  AutomationScripts/BitCoin Mining/bitcoin_mining.py
  AutomationScripts/BitCoin Mining/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#203 GUI Calendar
  GUIScripts/GUI Calendar/Images/output.png
  GUIScripts/GUI Calendar/README.md
  GUIScripts/GUI Calendar/gui_calendar.py
  GUIScripts/GUI Calendar/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#194 Minesweeper Game using 2D Python Implementation
  PyGamesScripts/Minesweeper/Images/GameOver.png
  PyGamesScripts/Minesweeper/Images/Input.png
  PyGamesScripts/Minesweeper/README.md
  PyGamesScripts/Minesweeper/minesweeper.py
  PyGamesScripts/Minesweeper/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#93 Calculator app added
  GUIScripts/Calculator App/Images/cak 3.png
  GUIScripts/Calculator App/Images/cal 1.png
  GUIScripts/Calculator App/Images/cal 2.png
  GUIScripts/Calculator App/README..md
  GUIScripts/Calculator App/calculator.py
Labels: LGMSOC21, 🟨 Level2

#182 COWIN API SCRIPT
  APIScripts/COWIN API/Images/img1.PNG
  APIScripts/COWIN API/Images/img2.PNG
  APIScripts/COWIN API/Images/img3.gif
  APIScripts/COWIN API/Images/img4.PNG
  APIScripts/COWIN API/README.md
  APIScripts/COWIN API/cowin_api.py
  APIScripts/COWIN API/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#187 Weather Report GUI script
  GUIScripts/Weather Report GUI/Images/clear sky.jpg
  GUIScripts/Weather Report GUI/Images/output1.PNG
  GUIScripts/Weather Report GUI/Images/output2.PNG
  GUIScripts/Weather Report GUI/Images/weather icon.png
  GUIScripts/Weather Report GUI/README.md
  GUIScripts/Weather Report GUI/requirements.txt
  GUIScripts/Weather Report GUI/weather_report.py
Labels: LGMSOC21, 🟧 Level3

#219 Move the Box
  PyGamesScripts/Move the Box/Images/after moving to down.png
  PyGamesScripts/Move the Box/Images/after moving to left.png
  PyGamesScripts/Move the Box/Images/after moving to right.png
  PyGamesScripts/Move the Box/Images/after moving to top.png
  PyGamesScripts/Move the Box/Images/before moving anywhere.png
  PyGamesScripts/Move the Box/README..md
  PyGamesScripts/Move the Box/move_the_box.py
Labels: LGMSOC21, 🟨 Level2

#214 Oddly Satisfying Game
  PyGamesScripts/Oddly Satisfying Game/Images/animation_img.PNG
  PyGamesScripts/Oddly Satisfying Game/Images/main_menu_img.PNG
  PyGamesScripts/Oddly Satisfying Game/README.md
  PyGamesScripts/Oddly Satisfying Game/oddly_satisfying_game.py
  PyGamesScripts/Oddly Satisfying Game/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#220 Sending HTML Email
  BasicPythonScripts/Sending HTML Email/Images/Demo Output.png
  BasicPythonScripts/Sending HTML Email/README.md
  BasicPythonScripts/Sending HTML Email/html_email.py
  BasicPythonScripts/Sending HTML Email/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#229 You_or_ME
  PyGamesScripts/You or Me/Images/game 1.png
  PyGamesScripts/You or Me/Images/game 2.png
  PyGamesScripts/You or Me/Images/game _you or me.gif
  PyGamesScripts/You or Me/README..md
  PyGamesScripts/You or Me/youorme.py
Labels: LGMSOC21, 🟨 Level2

#232 Tracking Phone Number
  BasicPythonScripts/Tracking Phone Number/Images/README.md
  BasicPythonScripts/Tracking Phone Number/Images/input(phone).png
  BasicPythonScripts/Tracking Phone Number/Images/output(phone).png
  BasicPythonScripts/Tracking Phone Number/README.md
  BasicPythonScripts/Tracking Phone Number/requirements.txt
  BasicPythonScripts/Tracking Phone Number/tracking_phone_number.py
Labels: LGMSOC21, 🟩 Level1

#230 Updating Sorting Algorithm Visualizer
  PyGamesScripts/Sorting Algorithm Visualizer/Bubble_Sort.ipynb
  PyGamesScripts/Sorting Algorithm Visualizer/Images/BubbleSort_1.png
  PyGamesScripts/Sorting Algorithm Visualizer/Images/BubbleSort_2.png
  PyGamesScripts/Sorting Algorithm Visualizer/Images/InsertionSort_1.png
  PyGamesScripts/Sorting Algorithm Visualizer/Images/InsertionSort_2.png
  PyGamesScripts/Sorting Algorithm Visualizer/Insertion_Sort.ipynb
  PyGamesScripts/Sorting Algorithm Visualizer/README.md
  PyGamesScripts/Sorting Algorithm Visualizer/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#238 All Information About Country
  BasicPythonScripts/Country Notifier/Images/README.md
  BasicPythonScripts/Country Notifier/Images/input_1(country).png
  BasicPythonScripts/Country Notifier/Images/input_2(country).png
  BasicPythonScripts/Country Notifier/Images/output(country).png
  BasicPythonScripts/Country Notifier/README.md
  BasicPythonScripts/Country Notifier/country_notifier.py
  BasicPythonScripts/Country Notifier/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#240 Enhanced the English dictionary
  GUIScripts/English Dictionary/Images/1.png
  GUIScripts/English Dictionary/Images/2.png
  GUIScripts/English Dictionary/Images/3.png
  GUIScripts/English Dictionary/Images/4.png
  GUIScripts/English Dictionary/Images/5.png
  GUIScripts/English Dictionary/Images/6.png
  GUIScripts/English Dictionary/Images/7.png
  GUIScripts/English Dictionary/Images/8.png
  GUIScripts/English Dictionary/README_enhanced.md
  GUIScripts/English Dictionary/Related/words.csv
  GUIScripts/English Dictionary/english_dictionary.py
  GUIScripts/English Dictionary/requirements.txt
Labels: LGMSOC21, 🟥 Level4

#250 Real-Time Currency Converter
  BasicPythonScripts/Real-Time Currency Converter/Images/on_compiling.png
  BasicPythonScripts/Real-Time Currency Converter/Images/on_wrong_response.png
  BasicPythonScripts/Real-Time Currency Converter/Images/working.png
  BasicPythonScripts/Real-Time Currency Converter/README.md
  BasicPythonScripts/Real-Time Currency Converter/currency_converter.py
  BasicPythonScripts/Real-Time Currency Converter/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#249 Movie Information Detailer
  BasicPythonScripts/Movie Information Detailer/Images/Output(movie).png
  BasicPythonScripts/Movie Information Detailer/Images/README.md
  BasicPythonScripts/Movie Information Detailer/README.md
  BasicPythonScripts/Movie Information Detailer/movie_information_detailer.py
  BasicPythonScripts/Movie Information Detailer/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#259 Created Digital clock using python GUI script
  GUIScripts/Digital Clock/Images/.gitkeep
  GUIScripts/Digital Clock/Images/Digital_clock_output.jpg
  GUIScripts/Digital Clock/README.md
  GUIScripts/Digital Clock/digital_clock.py
  GUIScripts/Digital Clock/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#258 Issue 185: Added Canny Edge Detection
  ImageProcessingScripts/Canny Edge Detection/Images/demo1.PNG
  ImageProcessingScripts/Canny Edge Detection/Images/demo2.PNG
  ImageProcessingScripts/Canny Edge Detection/Images/flower.jpg
  ImageProcessingScripts/Canny Edge Detection/Images/flower1.jpg
  ImageProcessingScripts/Canny Edge Detection/README.md
  ImageProcessingScripts/Canny Edge Detection/canny_edge.py
Labels: LGMSOC21, 🟩 Level1

#256 Url shortener
  APIScripts/URLShortener API/Images/output_ss.png
  APIScripts/URLShortener API/Images/short_ss.png
  APIScripts/URLShortener API/Images/urlopened_ss.png
  APIScripts/URLShortener API/README.md
  APIScripts/URLShortener API/url_shortener.py
Labels: LGMSOC21, 🟨 Level2

#245 Covid cases bot
  AutomationScripts/Covid Cases Bot/Covid-19_cases_notifier.py
  AutomationScripts/Covid Cases Bot/Images/screenshot.jpg
  AutomationScripts/Covid Cases Bot/README.md
  AutomationScripts/Covid Cases Bot/requirements.txt
  AutomationScripts/README.md
Labels: LGMSOC21, 🟨 Level2

#239 Notes panel
  GUIScripts/Notes Panel/Images/gif.gif
  GUIScripts/Notes Panel/Images/notes 1.png
  GUIScripts/Notes Panel/Images/notes 2.png
  GUIScripts/Notes Panel/README.md
  GUIScripts/Notes Panel/notes.py
  GUIScripts/Notes Panel/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#223 Login System
  GUIScripts/Event Handling/Images/output.png
  GUIScripts/Event Handling/README.md
  GUIScripts/Event Handling/event_handling.py
  GUIScripts/Event Handling/requirements.txt
  GUIScripts/Login System/Images/output.png
  GUIScripts/Login System/Login.txt
  GUIScripts/Login System/README.md
  GUIScripts/Login System/login_system.py
  GUIScripts/Login System/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#236 Add Bank Management System
  GUIScripts/Bank Managment Systems/Backend/backend.py
  GUIScripts/Bank Managment Systems/Frontend/frontend.py
  GUIScripts/Bank Managment Systems/Images/bank.PNG
  GUIScripts/Bank Managment Systems/Images/bank2.PNG
  GUIScripts/Bank Managment Systems/Images/bank3.PNG
  GUIScripts/Bank Managment Systems/Images/db.PNG
  GUIScripts/Bank Managment Systems/Images/db2.PNG
  GUIScripts/Bank Managment Systems/Images/db3.PNG
  GUIScripts/Bank Managment Systems/README.md
  GUIScripts/Bank Managment Systems/bankmanaging.db
  GUIScripts/README.md
Labels: LGMSOC21, 🟥 Level4

#242 Snake_game
  PyGamesScripts/Snake Game/Images
  PyGamesScripts/Snake Game/README.md
  PyGamesScripts/Snake Game/requirements.txt
  PyGamesScripts/Snake Game/snake_game.py
Labels: LGMSOC21, 🟨 Level2

#263 Image pyramiding
  ImageProcessingScripts/Image Pyramiding/Image Pyramiding.py
  ImageProcessingScripts/Image Pyramiding/Images/apple.jpg
  ImageProcessingScripts/Image Pyramiding/Images/file
  ImageProcessingScripts/Image Pyramiding/Images/orange.jpg
  ImageProcessingScripts/Image Pyramiding/Images/output.jpg
  ImageProcessingScripts/Image Pyramiding/README.md
Labels: LGMSOC21, 🟧 Level3

#271 Flames
  PyGamesScripts/Flames/Images/gif.gif
  PyGamesScripts/Flames/Images/input.png
  PyGamesScripts/Flames/Images/ouput.png
  PyGamesScripts/Flames/Images/over view.png
  PyGamesScripts/Flames/README.md
  PyGamesScripts/Flames/flames.py
Labels: LGMSOC21, 🟨 Level2

#269 Voting System
  BasicPythonScripts/Voting System/Images/README.md
  BasicPythonScripts/Voting System/Images/output_1(voting).png
  BasicPythonScripts/Voting System/Images/output_2(voting).png
  BasicPythonScripts/Voting System/README.md
  BasicPythonScripts/Voting System/requirements.txt
  BasicPythonScripts/Voting System/voting_system.py
Labels: LGMSOC21, 🟨 Level2

#288 Image 2 pencil sketch
  ImageProcessingScripts/Image 2 Pencil Sketch/Images/Captain_america.jpg
  ImageProcessingScripts/Image 2 Pencil Sketch/Images/sketch.png
  ImageProcessingScripts/Image 2 Pencil Sketch/README.md
  ImageProcessingScripts/Image 2 Pencil Sketch/image_2_sketch.py
  ImageProcessingScripts/Image 2 Pencil Sketch/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#294 Added a voice assistant using python
  AutomationScripts/Gwen - Voice Assistant/Gwen/Gwen.py
  AutomationScripts/Gwen - Voice Assistant/Gwen/api.py
  AutomationScripts/Gwen - Voice Assistant/Gwen/api.txt
  AutomationScripts/Gwen - Voice Assistant/Gwen/browser.py
  AutomationScripts/Gwen - Voice Assistant/Gwen/gmail.py
  AutomationScripts/Gwen - Voice Assistant/Gwen/weather.py
  AutomationScripts/Gwen - Voice Assistant/Gwen/youtube.py
  AutomationScripts/Gwen - Voice Assistant/Images/Gwen.png
  AutomationScripts/Gwen - Voice Assistant/README.md.md
  AutomationScripts/Gwen - Voice Assistant/requirements.txt
Labels: LGMSOC21, 🟥 Level4

#267 covid-19 cases using web scraping
  WebScrapingScripts/Covid Cases/Images/corona1.png
  WebScrapingScripts/Covid Cases/Images/corona2.png
  WebScrapingScripts/Covid Cases/Images/corona3.png
  WebScrapingScripts/Covid Cases/Images/corona4.png
  WebScrapingScripts/Covid Cases/README.md
  WebScrapingScripts/Covid Cases/covid19.py
  WebScrapingScripts/Covid Cases/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#297 Registration Form Interface
  GUIScripts/Registration Form/Images/Demo Output.png
  GUIScripts/Registration Form/README.md
  GUIScripts/Registration Form/registration_form.py
  GUIScripts/Registration Form/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#304 Added Image to Icon Converter in GUI Scripts
  GUIScripts/Image to Icon Converter/Images/1.jpg
  GUIScripts/Image to Icon Converter/Images/2.jpg
  GUIScripts/Image to Icon Converter/Images/3.jpg
  GUIScripts/Image to Icon Converter/Images/4.jpg
  GUIScripts/Image to Icon Converter/Images/5.jpg
  GUIScripts/Image to Icon Converter/Images/6.jpg
  GUIScripts/Image to Icon Converter/Images/7.jpg
  GUIScripts/Image to Icon Converter/Images/8.jpg
  GUIScripts/Image to Icon Converter/README.md
  GUIScripts/Image to Icon Converter/image_to_icon_converter.py
  GUIScripts/Image to Icon Converter/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#287 2048 game
  PyGamesScripts/2048/2048_game.py
  PyGamesScripts/2048/Images/lost.PNG
  PyGamesScripts/2048/Images/playing.PNG
  PyGamesScripts/2048/Images/startingWords.PNG
  PyGamesScripts/2048/Images/youlose.PNG
  PyGamesScripts/2048/README.md
  PyGamesScripts/2048/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#323 Adventure Based Game(Text Game)
  BasicPythonScripts/Adventure Based Game(Text Game)/Images/README.md
  BasicPythonScripts/Adventure Based Game(Text Game)/Images/output_1(adventure).png
  BasicPythonScripts/Adventure Based Game(Text Game)/Images/output_2(adventure).png
  BasicPythonScripts/Adventure Based Game(Text Game)/README.md
  BasicPythonScripts/Adventure Based Game(Text Game)/adventure_based_game(text game).py
  BasicPythonScripts/Adventure Based Game(Text Game)/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#322 More Chocolates Please Problem in Python
  BasicPythonScripts/More Chocolates Please!!!/Images/l3.png
  BasicPythonScripts/More Chocolates Please!!!/Images/l4.png
  BasicPythonScripts/More Chocolates Please!!!/README.md
  BasicPythonScripts/More Chocolates Please!!!/more_chocolates_please.py
Labels: LGMSOC21, 🟩 Level1

#327 Desktop Notification
  AutomationScripts/Desktop Notification/Images/README.md
  AutomationScripts/Desktop Notification/Images/output(desktop).png
  AutomationScripts/Desktop Notification/README.md
  AutomationScripts/Desktop Notification/desktop_notification.py
  AutomationScripts/Desktop Notification/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#260 Added Snakes and Ladders Game folder
  PyGamesScripts/Snakes and Ladders Game/Images/output.png
  PyGamesScripts/Snakes and Ladders Game/Images/snake-and-ladders.jpg
  PyGamesScripts/Snakes and Ladders Game/README.md
  PyGamesScripts/Snakes and Ladders Game/requirements.txt
  PyGamesScripts/Snakes and Ladders Game/snakes_and_ladders.py
Labels: LGMSOC21, 🟨 Level2

#329 Added Zodiac Sign Finder in Python
  GUIScripts/Zodiac Sign Finder/Images/1.jpg
  GUIScripts/Zodiac Sign Finder/Images/10.jpg
  GUIScripts/Zodiac Sign Finder/Images/11.jpg
  GUIScripts/Zodiac Sign Finder/Images/12.jpg
  GUIScripts/Zodiac Sign Finder/Images/13.jpg
  GUIScripts/Zodiac Sign Finder/Images/14.jpg
  GUIScripts/Zodiac Sign Finder/Images/15.jpg
  GUIScripts/Zodiac Sign Finder/Images/16.jpg
  GUIScripts/Zodiac Sign Finder/Images/17.jpg
  GUIScripts/Zodiac Sign Finder/Images/18.jpg
  GUIScripts/Zodiac Sign Finder/Images/19.jpg
  GUIScripts/Zodiac Sign Finder/Images/2.jpg
  GUIScripts/Zodiac Sign Finder/Images/3.jpg
  GUIScripts/Zodiac Sign Finder/Images/4.jpg
  GUIScripts/Zodiac Sign Finder/Images/5.jpg
  GUIScripts/Zodiac Sign Finder/Images/6.jpg
  GUIScripts/Zodiac Sign Finder/Images/7.jpg
  GUIScripts/Zodiac Sign Finder/Images/8.jpg
  GUIScripts/Zodiac Sign Finder/Images/9.jpg
  GUIScripts/Zodiac Sign Finder/Images/aquarius.gif
  GUIScripts/Zodiac Sign Finder/Images/aries.gif
  GUIScripts/Zodiac Sign Finder/Images/cancer.gif
  GUIScripts/Zodiac Sign Finder/Images/capricorn.gif
  GUIScripts/Zodiac Sign Finder/Images/gemini.gif
  GUIScripts/Zodiac Sign Finder/Images/leo.gif
  GUIScripts/Zodiac Sign Finder/Images/libra.gif
  GUIScripts/Zodiac Sign Finder/Images/pisces.gif
  GUIScripts/Zodiac Sign Finder/Images/sagittarius.gif
  GUIScripts/Zodiac Sign Finder/Images/scorpio.gif
  GUIScripts/Zodiac Sign Finder/Images/taurus.gif
  GUIScripts/Zodiac Sign Finder/Images/virgo.gif
  GUIScripts/Zodiac Sign Finder/Images/zodiac.jpg
  GUIScripts/Zodiac Sign Finder/README.md
  GUIScripts/Zodiac Sign Finder/requirements.txt
  GUIScripts/Zodiac Sign Finder/zodiac_sign_finder.py
Labels: LGMSOC21, 🟧 Level3

#336 Event Handling
  Event Handling/Images/output.png
  Event Handling/README.md
  Event Handling/event_handling.py
  Event Handling/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#337 Job Search Tool
  WebScrapingScripts/Job Search Tool/Images/output.PNG
  WebScrapingScripts/Job Search Tool/README.md
  WebScrapingScripts/Job Search Tool/Requirements.txt
  WebScrapingScripts/Job Search Tool/job_search_tool.py
Labels: LGMSOC21, 🟨 Level2

#296 Black Jack Game added
  PyGamesScripts/Black Jack Game/Images/screenshot.PNG
  PyGamesScripts/Black Jack Game/README.md
  PyGamesScripts/Black Jack Game/art.py
  PyGamesScripts/Black Jack Game/blackjack_game.py
  PyGamesScripts/Black Jack Game/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#339 Wifi Password Fetcher
  GUIScripts/Wifi Password Fetcher/Images/output_1(wifi).png
  GUIScripts/Wifi Password Fetcher/Images/output_2(wifi).png
  GUIScripts/Wifi Password Fetcher/README.md
  GUIScripts/Wifi Password Fetcher/requirements.txt
  GUIScripts/Wifi Password Fetcher/wifi_password_fetcher.py
Labels: LGMSOC21, 🟨 Level2

#353 Caterpillar Game GUI
  GUIScripts/Caterpillar Game GUI/Images/output(caterpillar_ending).png
  GUIScripts/Caterpillar Game GUI/Images/output(caterpillar_going).png
  GUIScripts/Caterpillar Game GUI/Images/output(caterpillar_starting).png
  GUIScripts/Caterpillar Game GUI/README.md
  GUIScripts/Caterpillar Game GUI/caterpillar_game_gui.py
  GUIScripts/Caterpillar Game GUI/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#352 Current Time Stamps
  AutomationScripts/Current Time Stamps/Images/Output.png
  AutomationScripts/Current Time Stamps/README.md
  AutomationScripts/Current Time Stamps/current_time_stamps.py
  AutomationScripts/Current Time Stamps/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#281 Tic_Tac_Toe_game
  PyGamesScripts/TicTacToe Game/requirements.txt
  PyGamesScripts/TicTacToe Game/tictactoe_game.py
  PyGamesScripts/TicTacToe game/Images/Game1.png
  PyGamesScripts/TicTacToe game/Images/Game2.png
  PyGamesScripts/TicTacToe game/README.md
Labels: LGMSOC21, 🟨 Level2

#328 Added Website Blocker
  AutomationScripts/Website Blocker/Images/UI1.png
  AutomationScripts/Website Blocker/Images/UI2.png
  AutomationScripts/Website Blocker/Images/UI3.png
  AutomationScripts/Website Blocker/README.md
  AutomationScripts/Website Blocker/requirements.txt
  AutomationScripts/Website Blocker/website_blocker.py
Labels: LGMSOC21, 🟧 Level3

#330 Integer to Roman numerals
  BasicPythonScripts/Integer  to RomanNumeral/Images/Screenshot (93).png
  BasicPythonScripts/Integer To Roman Numeral/Images/Screenshot of the output.png
  BasicPythonScripts/Integer To Roman Numeral/README.md
  BasicPythonScripts/Integer To Roman Numeral/integer _to_roman_numeral.py
  BasicPythonScripts/Integer To Roman Numeral/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#340 Added checklist app
  GUIScripts/Checklist App/Images/1.jpg
  GUIScripts/Checklist App/README.md
  GUIScripts/Checklist App/checklist_app.py
  GUIScripts/Checklist App/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#361 Encode Decode
  BasicPythonScripts/Encode Decode/Encode.py
  BasicPythonScripts/Encode Decode/Images/OVERVIEW.png
  BasicPythonScripts/Encode Decode/Images/invalid.png
  BasicPythonScripts/Encode Decode/README.md
  BasicPythonScripts/Encode Decode/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#362 Levels and Points #303
  README.md
Labels: LGMSOC21, 🟪 Level0

#368 Backup WhatsApp Chats To Excel Sheet
  AutomationScripts/WhatsApp Backup to Excel/Images/Output.jpg
  AutomationScripts/WhatsApp Backup to Excel/README.md
  AutomationScripts/WhatsApp Backup to Excel/requirements.txt
  AutomationScripts/WhatsApp Backup to Excel/whatsapp.py
Labels: LGMSOC21, 🟨 Level2

#367 Added Missing Alphabet Game in PyGames Script
  PyGamesScripts/Missing Alphabet Game/Images/1.jpg
  PyGamesScripts/Missing Alphabet Game/Images/2.jpg
  PyGamesScripts/Missing Alphabet Game/Images/3.jpg
  PyGamesScripts/Missing Alphabet Game/Images/4.jpg
  PyGamesScripts/Missing Alphabet Game/Images/5.jpg
  PyGamesScripts/Missing Alphabet Game/Images/6.jpg
  PyGamesScripts/Missing Alphabet Game/Images/7.jpg
  PyGamesScripts/Missing Alphabet Game/Images/missing.jpg
  PyGamesScripts/Missing Alphabet Game/Images/score1.gif
  PyGamesScripts/Missing Alphabet Game/README.md
  PyGamesScripts/Missing Alphabet Game/country_name.csv
  PyGamesScripts/Missing Alphabet Game/missing_alphabet_game.py
  PyGamesScripts/Missing Alphabet Game/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#356 Added the splash screen in Zodiac Sign Finder in GUIScripts
  GUIScripts/Zodiac Sign Finder/Images/splash.gif
  GUIScripts/Zodiac Sign Finder/README_enhanced.md
  GUIScripts/Zodiac Sign Finder/requirements.txt
  GUIScripts/Zodiac Sign Finder/zodiac_sign_finder.py
Labels: LGMSOC21, enhancement, 🟨 Level2

#351 Reddit Bot #349
  BasicPythonScripts/Reddit Bot/Images/README.md
  BasicPythonScripts/Reddit Bot/Images/bot.png
  BasicPythonScripts/Reddit Bot/README.md
  BasicPythonScripts/Reddit Bot/config.py
  BasicPythonScripts/Reddit Bot/reddit_bot.py
  BasicPythonScripts/Reddit Bot/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#366 Py-Browser - Web Browser using Python
  GUIScripts/PyBrowser/Images/web.png
  GUIScripts/PyBrowser/README.md
  GUIScripts/PyBrowser/protocol.py
  GUIScripts/PyBrowser/requirements.txt
  GUIScripts/PyBrowser/web_browser.py
Labels: LGMSOC21, 🟧 Level3

#374 Created Music player using pygame and tkinter
  BasicPythonScripts/Music Player/Images/music_player.jpg
  BasicPythonScripts/Music Player/README.md
  BasicPythonScripts/Music Player/music_player.py
  BasicPythonScripts/Music Player/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#377 Crack Any Password
  AutomationScripts/Current Time Stamps/README.md
  BasicPythonScripts/Crack Any Password/Images/output.png
  BasicPythonScripts/Crack Any Password/README.md
  BasicPythonScripts/Crack Any Password/crack_any_password.py
  BasicPythonScripts/Crack Any Password/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#382 Added End Result Predicitor in Tic Tac Toe game in Pygames Scripts
  PyGamesScripts/TicTacToe Game/Images/1.jpg
  PyGamesScripts/TicTacToe Game/Images/10.jpg
  PyGamesScripts/TicTacToe Game/Images/11.jpg
  PyGamesScripts/TicTacToe Game/Images/2.jpg
  PyGamesScripts/TicTacToe Game/Images/3.jpg
  PyGamesScripts/TicTacToe Game/Images/4.jpg
  PyGamesScripts/TicTacToe Game/Images/5.jpg
  PyGamesScripts/TicTacToe Game/Images/6.jpg
  PyGamesScripts/TicTacToe Game/Images/7.jpg
  PyGamesScripts/TicTacToe Game/Images/8.jpg
  PyGamesScripts/TicTacToe Game/Images/9.jpg
  PyGamesScripts/TicTacToe Game/Images/board.png
  PyGamesScripts/TicTacToe Game/Images/empty.jpg
  PyGamesScripts/TicTacToe Game/Images/o.jpg
  PyGamesScripts/TicTacToe Game/Images/x.jpg
  PyGamesScripts/TicTacToe Game/README_enhanced.md
  PyGamesScripts/TicTacToe Game/end_result_predictor.py
  PyGamesScripts/TicTacToe Game/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#387 Added automatic update of contributors list in Readme file
  README.md
Labels: LGMSOC21, 🟪 Level0

#389 Mobile Recharge Plan Detailer
  WebScrapingScripts/Mobile Recharge Plan Detailer/Images/output_1(mobile).png
  WebScrapingScripts/Mobile Recharge Plan Detailer/Images/output_2(mobile).png
  WebScrapingScripts/Mobile Recharge Plan Detailer/README.md
  WebScrapingScripts/Mobile Recharge Plan Detailer/mobile_recharge_plan_detailer.py
  WebScrapingScripts/Mobile Recharge Plan Detailer/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#360 Added the splash screen and logo to the title bar in Calculator App under GUI Scripts
  GUIScripts/Calculator App/Media/Added Logo.png
  GUIScripts/Calculator App/Media/Logo_CalculatorApp.gif
  GUIScripts/Calculator App/Media/Resized the buttons.png
  GUIScripts/Calculator App/Media/Splash Screen Functioning.mp4
  GUIScripts/Calculator App/Media/Splash Screen_Calculator App.gif
  GUIScripts/Calculator App/README_enhanced.md
  GUIScripts/Calculator App/calculator.py
Labels: LGMSOC21, enhancement, 🟧 Level3

#385 Creating Address Book
  GUIScripts/Address Book/Images/Demo Output.png
  GUIScripts/Address Book/README.md
  GUIScripts/Address Book/address_book.py
  GUIScripts/Address Book/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#394 Email Sender In Bulk
  AutomationScripts/Email Sender In Bulk/Images/README.md
  AutomationScripts/Email Sender In Bulk/Images/input(email).png
  AutomationScripts/Email Sender In Bulk/Images/output(email).png
  AutomationScripts/Email Sender In Bulk/README.md
  AutomationScripts/Email Sender In Bulk/email.csv
  AutomationScripts/Email Sender In Bulk/email_sender_in_bulk.py
  AutomationScripts/Email Sender In Bulk/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#405 Added Spelling Corrector Script in GUI Scripts
  GUIScripts/Spelling Corrector/Images/1.jpg
  GUIScripts/Spelling Corrector/Images/2.jpg
  GUIScripts/Spelling Corrector/Images/3.jpg
  GUIScripts/Spelling Corrector/Images/4.jpg
  GUIScripts/Spelling Corrector/Images/5.jpg
  GUIScripts/Spelling Corrector/Images/spell.jpg
  GUIScripts/Spelling Corrector/README.md
  GUIScripts/Spelling Corrector/requirements.txt
  GUIScripts/Spelling Corrector/spelling_corrector.py
Labels: LGMSOC21, 🟨 Level2

#404 Age Predictor Chatbot
  BasicPythonScripts/Age Predictor Chatbot/Images/output_1(age).png
  BasicPythonScripts/Age Predictor Chatbot/Images/output_2(age).png
  BasicPythonScripts/Age Predictor Chatbot/README.md
  BasicPythonScripts/Age Predictor Chatbot/age_predictor_chatbot.py
  BasicPythonScripts/Age Predictor Chatbot/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#403 Added Time Zone Converter in GUI Scripts
  GUIScripts/Time Zone Converter/Images/1.jpg
  GUIScripts/Time Zone Converter/Images/2.jpg
  GUIScripts/Time Zone Converter/Images/3.jpg
  GUIScripts/Time Zone Converter/Images/4.jpg
  GUIScripts/Time Zone Converter/Images/5.jpg
  GUIScripts/Time Zone Converter/Images/6.jpg
  GUIScripts/Time Zone Converter/Images/time.gif
  GUIScripts/Time Zone Converter/README.md
  GUIScripts/Time Zone Converter/conversion.csv
  GUIScripts/Time Zone Converter/requirements.txt
  GUIScripts/Time Zone Converter/time_zone_converter.py
Labels: LGMSOC21, 🟨 Level2

#401 Created Countdown timer for the event
  GUIScripts/Countdown Timer/Images/countdown_timer.jpg
  GUIScripts/Countdown Timer/Images/countdown_timer_user_input.jpg
  GUIScripts/Countdown Timer/README.md
  GUIScripts/Countdown Timer/countdown_timer.py
  GUIScripts/Countdown Timer/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#399 Open WebCam
  BasicPythonScripts/Open WebCam/Images/output.png
  BasicPythonScripts/Open WebCam/README.md
  BasicPythonScripts/Open WebCam/open_webcam.py
  BasicPythonScripts/Open WebCam/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#412 added Air canvas
  ImageProcessingScripts/Air Canvas/Images/output.png
  ImageProcessingScripts/Air Canvas/README.md
  ImageProcessingScripts/Air Canvas/air_canvas.py
  ImageProcessingScripts/Air Canvas/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#418 Library Management GUI
  GUIScripts/Library Management GUI/Images/README.md
  GUIScripts/Library Management GUI/Images/input_1(library).png
  GUIScripts/Library Management GUI/Images/input_2(library).png
  GUIScripts/Library Management GUI/Images/output(library).png
  GUIScripts/Library Management GUI/README.md
  GUIScripts/Library Management GUI/library_management_gui.py
  GUIScripts/Library Management GUI/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#413 Whatsapp Automation
  AutomationScripts/WhatsApp Automation/Images/output1.png
  AutomationScripts/WhatsApp Automation/Images/output2.png
  AutomationScripts/WhatsApp Automation/Images/whatsapp_output.png
  AutomationScripts/WhatsApp Automation/README.md
  AutomationScripts/WhatsApp Automation/requirements.txt
  AutomationScripts/WhatsApp Automation/whatsapp.py
Labels: LGMSOC21, 🟩 Level1

#350 Temperature Converter
  BasicPythonScripts/Temperature Conveter/Images/Program Stimulation.png
  BasicPythonScripts/Temperature Conveter/Images/Temp.png
  BasicPythonScripts/Temperature Conveter/README.md
  BasicPythonScripts/Temperature Conveter/temperature_converter.py
Labels: LGMSOC21, 🟨 Level2

#423 Added Quiz Game in GUIScripts
  GUIScripts/Quiz Game/Images/1.jpg
  GUIScripts/Quiz Game/Images/10.jpg
  GUIScripts/Quiz Game/Images/2.jpg
  GUIScripts/Quiz Game/Images/3.jpg
  GUIScripts/Quiz Game/Images/4.jpg
  GUIScripts/Quiz Game/Images/5.jpg
  GUIScripts/Quiz Game/Images/6.jpg
  GUIScripts/Quiz Game/Images/7.jpg
  GUIScripts/Quiz Game/Images/8.jpg
  GUIScripts/Quiz Game/Images/9.jpg
  GUIScripts/Quiz Game/Images/quiz.gif
  GUIScripts/Quiz Game/Images/quiz.jpg
  GUIScripts/Quiz Game/Images/score1.gif
  GUIScripts/Quiz Game/README.md
  GUIScripts/Quiz Game/data.json
  GUIScripts/Quiz Game/quiz_game.py
  GUIScripts/Quiz Game/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#425 Gold Price Fetcher
  WebScrapingScripts/Gold Price Fetcher/Images/README.md
  WebScrapingScripts/Gold Price Fetcher/Images/input(gold).png
  WebScrapingScripts/Gold Price Fetcher/Images/output(gold).png
  WebScrapingScripts/Gold Price Fetcher/Images/website(gold).png
  WebScrapingScripts/Gold Price Fetcher/README.md
  WebScrapingScripts/Gold Price Fetcher/gold_price_fetcher.py
  WebScrapingScripts/Gold Price Fetcher/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#428 Added Part Of Speech Calculator in GUIScript
  GUIScripts/Part Of Speeech Calculator/Images/1.jpg
  GUIScripts/Part Of Speeech Calculator/Images/2.jpg
  GUIScripts/Part Of Speeech Calculator/Images/3.jpg
  GUIScripts/Part Of Speeech Calculator/Images/4.jpg
  GUIScripts/Part Of Speeech Calculator/Images/5.jpg
  GUIScripts/Part Of Speeech Calculator/README.md
  GUIScripts/Part Of Speeech Calculator/part_of_speech_calculator.py
  GUIScripts/Part Of Speeech Calculator/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#437 Added Get Location of any Country in GUIScripts
  GUIScripts/Get Location of any Country/Images/1.jpg
  GUIScripts/Get Location of any Country/Images/2.jpg
  GUIScripts/Get Location of any Country/Images/3.jpg
  GUIScripts/Get Location of any Country/Images/4.jpg
  GUIScripts/Get Location of any Country/Images/5.jpg
  GUIScripts/Get Location of any Country/Images/6.jpg
  GUIScripts/Get Location of any Country/Images/7.jpg
  GUIScripts/Get Location of any Country/Images/latlong.gif
  GUIScripts/Get Location of any Country/README.md
  GUIScripts/Get Location of any Country/get_location_of_any_country.py
  GUIScripts/Get Location of any Country/requirements.txt
  GUIScripts/Get Location of any Country/world_location.csv
Labels: LGMSOC21, 🟨 Level2

#431 BMI Calculator GUI
  GUIScripts/BMI Calculator GUI/Media/BMI Calculator Function.mp4
  GUIScripts/BMI Calculator GUI/Media/BMI Calculator_logo.gif
  GUIScripts/BMI Calculator GUI/Media/BMI_Splash Screen.gif
  GUIScripts/BMI Calculator GUI/Media/CalculatedValue.png
  GUIScripts/BMI Calculator GUI/Media/ExitScreen.png
  GUIScripts/BMI Calculator GUI/Media/FirstScreen.png
  GUIScripts/BMI Calculator GUI/Media/InputScreen.png
  GUIScripts/BMI Calculator GUI/README.md
  GUIScripts/BMI Calculator GUI/bmi_calculator.py
  GUIScripts/BMI Calculator GUI/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#424 Preview your link
  BasicPythonScripts/Preview your link/Images/preview.png
  BasicPythonScripts/Preview your link/README.md
  BasicPythonScripts/Preview your link/link_preview.py
  BasicPythonScripts/Preview your link/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#346 Added Code for Text Extractor from PDF
  BasicPythonScripts/Text Extractor from PDF/Images/Output.png
  BasicPythonScripts/Text Extractor from PDF/Images/PDF File.png
  BasicPythonScripts/Text Extractor from PDF/README.md
  BasicPythonScripts/Text Extractor from PDF/requirements.txt
  BasicPythonScripts/Text Extractor from PDF/text_extractor.py
Labels: LGMSOC21, 🟨 Level2

#443 Zip Files Extractor
  BasicPythonScripts/Zip Files Extractor/Images/output(unzip).png
  BasicPythonScripts/Zip Files Extractor/Images/sample_zip.png
  BasicPythonScripts/Zip Files Extractor/README.md
  BasicPythonScripts/Zip Files Extractor/requirements.txt
  BasicPythonScripts/Zip Files Extractor/sample.zip
  BasicPythonScripts/Zip Files Extractor/zip_files_extractor.py
Labels: LGMSOC21, 🟩 Level1

#422 Rolling Dice game added
  PyGamesScripts/Rolling Dice/Images/Screenshot_1.jpg
  PyGamesScripts/Rolling Dice/Images/Screenshot_2.jpg
  PyGamesScripts/Rolling Dice/README.md
  PyGamesScripts/Rolling Dice/Rolling_Dice.py
  PyGamesScripts/Rolling Dice/requirement.txt
Labels: LGMSOC21, 🟩 Level1

#442 Added Search Implementation in GUIScripts
  GUIScripts/Search Implementation/Images/1.jpg
  GUIScripts/Search Implementation/Images/2.jpg
  GUIScripts/Search Implementation/Images/3.jpg
  GUIScripts/Search Implementation/Images/4.jpg
  GUIScripts/Search Implementation/Images/5.jpg
  GUIScripts/Search Implementation/Images/6.jpg
  GUIScripts/Search Implementation/Images/7.jpg
  GUIScripts/Search Implementation/README.md
  GUIScripts/Search Implementation/requirements.txt
  GUIScripts/Search Implementation/search_implementation.py
  GUIScripts/Search Implementation/words.csv
Labels: LGMSOC21, 🟧 Level3

#441 Word Transfer
  BasicPythonScripts/Word Transfer/Images/word_transfer_client_ss_1.jpg
  BasicPythonScripts/Word Transfer/Images/word_transfer_client_ss_2.jpg
  BasicPythonScripts/Word Transfer/Images/word_transfer_server_ss.jpg
  BasicPythonScripts/Word Transfer/README.md
  BasicPythonScripts/Word Transfer/word_tansfer_server.py
  BasicPythonScripts/Word Transfer/word_transfer_client.py
  BasicPythonScripts/Word Transfer/words.py
Labels: LGMSOC21, 🟨 Level2

#448 Created Egg catcher game
  GUIScripts/Egg Catcher Game/Images/egg_catcher_game.jpg
  GUIScripts/Egg Catcher Game/Images/game_over.jpg
  GUIScripts/Egg Catcher Game/README.md
  GUIScripts/Egg Catcher Game/egg_catcher.py
  GUIScripts/Egg Catcher Game/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#452 Wordcloud
  BasicPythonScripts/Word Cloud/Images/output(wordcloud).png
  BasicPythonScripts/Word Cloud/Images/output_1(wordcloud).png
  BasicPythonScripts/Word Cloud/README.md
  BasicPythonScripts/Word Cloud/requirements.txt
  BasicPythonScripts/Word Cloud/textfile.txt
  BasicPythonScripts/Word Cloud/word_cloud.py
Labels: LGMSOC21, 🟩 Level1

#438 added Turtle race Game
  PyGamesScripts/Turtle Race/Images/screenshot.PNG
  PyGamesScripts/Turtle Race/README.md
  PyGamesScripts/Turtle Race/requirenments.txt
  PyGamesScripts/Turtle Race/turtle_race.py
Labels: LGMSOC21, 🟩 Level1

#455 Added Indian Food Information in GUIScripts
  GUIScripts/Indian Food Information/Images/1.jpg
  GUIScripts/Indian Food Information/Images/2.jpg
  GUIScripts/Indian Food Information/Images/3.jpg
  GUIScripts/Indian Food Information/Images/4.jpg
  GUIScripts/Indian Food Information/Images/5.jpg
  GUIScripts/Indian Food Information/Images/6.jpg
  GUIScripts/Indian Food Information/Images/7.jpg
  GUIScripts/Indian Food Information/Images/food.gif
  GUIScripts/Indian Food Information/README.md
  GUIScripts/Indian Food Information/indian_food.csv
  GUIScripts/Indian Food Information/indian_food_information.py
  GUIScripts/Indian Food Information/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#461 ISS Tracker and current onboard crew info
  AutomationScripts/ISS Tracker/Images & Video/iss crew info.png
  AutomationScripts/ISS Tracker/Images & Video/iss live video.gif
  AutomationScripts/ISS Tracker/Images & Video/iss location map.png
  AutomationScripts/ISS Tracker/Images & Video/iss.gif
  AutomationScripts/ISS Tracker/Images & Video/map.gif
  AutomationScripts/ISS Tracker/README.md
  AutomationScripts/ISS Tracker/iss.txt
  AutomationScripts/ISS Tracker/iss_tracker.py
  AutomationScripts/ISS Tracker/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#462 File Transfer
  BasicPythonScripts/File Transfer/Images/file_transfer_client_ss.jpg
  BasicPythonScripts/File Transfer/Images/file_transfer_server_ss_1.jpg
  BasicPythonScripts/File Transfer/Images/file_transfer_server_ss_2.jpg
  BasicPythonScripts/File Transfer/README.md
  BasicPythonScripts/File Transfer/Requirements.txt
  BasicPythonScripts/File Transfer/data.txt
  BasicPythonScripts/File Transfer/file_transfer_client.py
  BasicPythonScripts/File Transfer/file_transfer_server.py
Labels: LGMSOC21, 🟨 Level2

#463 Issue 414: Added Image Stitching
  ImageProcessingScripts/Image Stitching/Images/hill1.jpg
  ImageProcessingScripts/Image Stitching/Images/hill2.jpg
  ImageProcessingScripts/Image Stitching/Images/matchedpoints.PNG
  ImageProcessingScripts/Image Stitching/Images/matchedpoints1.PNG
  ImageProcessingScripts/Image Stitching/Images/matchedpoints2.PNG
  ImageProcessingScripts/Image Stitching/Images/matching.PNG
  ImageProcessingScripts/Image Stitching/Images/matching1.PNG
  ImageProcessingScripts/Image Stitching/Images/matching2.PNG
  ImageProcessingScripts/Image Stitching/Images/result.PNG
  ImageProcessingScripts/Image Stitching/Images/result1.PNG
  ImageProcessingScripts/Image Stitching/Images/result2.PNG
  ImageProcessingScripts/Image Stitching/Images/room1.jpg
  ImageProcessingScripts/Image Stitching/Images/room2.jpg
  ImageProcessingScripts/Image Stitching/Images/s1.jpg
  ImageProcessingScripts/Image Stitching/Images/s2.jpg
  ImageProcessingScripts/Image Stitching/README.md
  ImageProcessingScripts/Image Stitching/image_stitching.py
  ImageProcessingScripts/Image Stitching/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#469 Stock Visualiser
  BasicPythonScripts/Stock Visualiser/Images/output_1(stock).png
  BasicPythonScripts/Stock Visualiser/Images/output_2(stock).png
  BasicPythonScripts/Stock Visualiser/Images/output_3(stock).png
  BasicPythonScripts/Stock Visualiser/README.md
  BasicPythonScripts/Stock Visualiser/requirements.txt
  BasicPythonScripts/Stock Visualiser/stock_visualiser.py
Labels: LGMSOC21, 🟩 Level1

#484 Added Direct Flight Route Finder in GUIScripts
  GUIScripts/Direct Flight Route Finder/Images/1.jpg
  GUIScripts/Direct Flight Route Finder/Images/2.jpg
  GUIScripts/Direct Flight Route Finder/Images/3.jpg
  GUIScripts/Direct Flight Route Finder/Images/4.jpg
  GUIScripts/Direct Flight Route Finder/Images/5.jpg
  GUIScripts/Direct Flight Route Finder/Images/6.jpg
  GUIScripts/Direct Flight Route Finder/Images/flight.gif
  GUIScripts/Direct Flight Route Finder/README.md
  GUIScripts/Direct Flight Route Finder/direct_flight_route_finder.py
  GUIScripts/Direct Flight Route Finder/flight1.csv
  GUIScripts/Direct Flight Route Finder/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#483 Added World Bank GDP Ranking in GUIScripts
  GUIScripts/World Bank GDP Ranking/Images/1.jpg
  GUIScripts/World Bank GDP Ranking/Images/2.jpg
  GUIScripts/World Bank GDP Ranking/Images/3.jpg
  GUIScripts/World Bank GDP Ranking/Images/4.jpg
  GUIScripts/World Bank GDP Ranking/Images/5.jpg
  GUIScripts/World Bank GDP Ranking/Images/6.jpg
  GUIScripts/World Bank GDP Ranking/Images/7.jpg
  GUIScripts/World Bank GDP Ranking/Images/gdp.gif
  GUIScripts/World Bank GDP Ranking/README.md
  GUIScripts/World Bank GDP Ranking/gdp.csv
  GUIScripts/World Bank GDP Ranking/requirements.txt
  GUIScripts/World Bank GDP Ranking/world_bank_gdp_ranking.py
Labels: LGMSOC21, 🟨 Level2

#477 Added Wikipedia GUI
  GUIScripts/Wikipedia GUI/Images/image_1.JPG
  GUIScripts/Wikipedia GUI/Images/image_2.JPG
  GUIScripts/Wikipedia GUI/README.md
  GUIScripts/Wikipedia GUI/requirements.txt
  GUIScripts/Wikipedia GUI/wikipedia_gui.py
Labels: LGMSOC21, 🟨 Level2

#473 Internet Speed Tracker GUI Script
  GUIScripts/Internet Speed Tracker/Media/First Screen.png
  GUIScripts/Internet Speed Tracker/Media/Functioning.mp4
  GUIScripts/Internet Speed Tracker/Media/Output Screen.png
  GUIScripts/Internet Speed Tracker/Media/SpeedTest Logo.gif
  GUIScripts/Internet Speed Tracker/README.md
  GUIScripts/Internet Speed Tracker/internet_speedtest.py
  GUIScripts/Internet Speed Tracker/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#451 Days Finder In A Month
  BasicPythonScripts/Finding Number of Days in a Month/Images/Day Finder.png
  BasicPythonScripts/Finding Number of Days in a Month/Images/Number_of_days.png
  BasicPythonScripts/Finding Number of Days in a Month/README.md
  BasicPythonScripts/Finding Number of Days in a Month/days_finder.py
  BasicPythonScripts/Finding Number of Days in a Month/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#472 Wikipedia Summary
  GUIScripts/Wikipedia Summary/Images/output gif.gif
  GUIScripts/Wikipedia Summary/Images/output screenshot 1.png
  GUIScripts/Wikipedia Summary/Images/output screenshot 2.png
  GUIScripts/Wikipedia Summary/README.md
  GUIScripts/Wikipedia Summary/Wikipedia_Summary.py
  GUIScripts/Wikipedia Summary/requirement.txt
Labels: LGMSOC21, 🟩 Level1

#440 Added Chess Game
  PyGamesScripts/Chess Game/Images/img.jpg
  PyGamesScripts/Chess Game/README.md
  PyGamesScripts/Chess Game/chess_game.py
  PyGamesScripts/Chess Game/requirements.txt
Labels: LGMSOC21, 🟧 Level3

#489 Air Quality Detector(API)
  APIScripts/Air Quality Detector/Images/output(air).png
  APIScripts/Air Quality Detector/README.md
  APIScripts/Air Quality Detector/air_quality_detector.py
  APIScripts/Air Quality Detector/requirements.txt
Labels: LGMSOC21, 🟩 Level1

#490 Added SpaceX Mission Detailer in Python Script
  GUIScripts/SpaceX Mission Detailer/Images/1.jpg
  GUIScripts/SpaceX Mission Detailer/Images/2.jpg
  GUIScripts/SpaceX Mission Detailer/Images/3.jpg
  GUIScripts/SpaceX Mission Detailer/Images/4.jpg
  GUIScripts/SpaceX Mission Detailer/Images/5.jpg
  GUIScripts/SpaceX Mission Detailer/Images/6.jpg
  GUIScripts/SpaceX Mission Detailer/Images/7.jpg
  GUIScripts/SpaceX Mission Detailer/Images/spacex.gif
  GUIScripts/SpaceX Mission Detailer/README.md
  GUIScripts/SpaceX Mission Detailer/requirements.txt
  GUIScripts/SpaceX Mission Detailer/spaceX_data.csv
  GUIScripts/SpaceX Mission Detailer/spacex_mission_detailer.py
Labels: LGMSOC21, 🟨 Level2

#498 Added Periodic Table Elements Information in GUISripts
  GUIScripts/Periodic Table Elements Information/Images/1.jpg
  GUIScripts/Periodic Table Elements Information/Images/2.jpg
  GUIScripts/Periodic Table Elements Information/Images/3.jpg
  GUIScripts/Periodic Table Elements Information/Images/4.jpg
  GUIScripts/Periodic Table Elements Information/Images/5.jpg
  GUIScripts/Periodic Table Elements Information/Images/6.jpg
  GUIScripts/Periodic Table Elements Information/Images/periodic.gif
  GUIScripts/Periodic Table Elements Information/README.md
  GUIScripts/Periodic Table Elements Information/periodic_table.csv
  GUIScripts/Periodic Table Elements Information/periodic_table_elements_information.py
  GUIScripts/Periodic Table Elements Information/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#496 Fidget Spinner
  BasicPythonScripts/Fidget Spinner/Images/output(fidget).png
  BasicPythonScripts/Fidget Spinner/README.md
  BasicPythonScripts/Fidget Spinner/fidget_spinner.py
  BasicPythonScripts/Fidget Spinner/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#458 added age calculator feature
  GUIScripts/Age Calculator/Images/output.png
  GUIScripts/Age Calculator/Images/sample.png
  GUIScripts/Age Calculator/README.md
  GUIScripts/Age Calculator/age_calculator.py
  GUIScripts/Age Calculator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#505 Added Indian University NIRF Ranking in GUIScripts
  GUIScripts/Indian University NIRF Ranking/Images/1.jpg
  GUIScripts/Indian University NIRF Ranking/Images/2.jpg
  GUIScripts/Indian University NIRF Ranking/Images/3.jpg
  GUIScripts/Indian University NIRF Ranking/Images/4.jpg
  GUIScripts/Indian University NIRF Ranking/Images/5.jpg
  GUIScripts/Indian University NIRF Ranking/Images/6.jpg
  GUIScripts/Indian University NIRF Ranking/Images/7.jpg
  GUIScripts/Indian University NIRF Ranking/Images/8.jpg
  GUIScripts/Indian University NIRF Ranking/Images/university.gif
  GUIScripts/Indian University NIRF Ranking/README.md
  GUIScripts/Indian University NIRF Ranking/engineering.csv
  GUIScripts/Indian University NIRF Ranking/indian_university_NIRF_ranking.py
  GUIScripts/Indian University NIRF Ranking/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#507 Instagram Bot
  AutomationScripts/Instagram Bot/Images/insta_followers.png
  AutomationScripts/Instagram Bot/Images/insta_upload.png
  AutomationScripts/Instagram Bot/README.md
  AutomationScripts/Instagram Bot/instagram_bot.py
  AutomationScripts/Instagram Bot/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#502 Acronym Of The Word
  BasicPythonScripts/Acronym of The Word/Images/Output.png
  BasicPythonScripts/Acronym of The Word/README.md
  BasicPythonScripts/Acronym of The Word/acronym_of_the_word.py
  BasicPythonScripts/Acronym of The Word/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#504 Send Push Notification To Your Phone
  AutomationScripts/Push Notification/Images/output.gif
  AutomationScripts/Push Notification/Images/output.png
  AutomationScripts/Push Notification/README.md
  AutomationScripts/Push Notification/pushbullet_notification.py
  AutomationScripts/Push Notification/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#510 Split Each Excel Sheet Into Separate Excel Files
  AutomationScripts/Split Excel File/Images/output_1.jpg
  AutomationScripts/Split Excel File/Images/output_2.jpg
  AutomationScripts/Split Excel File/README.md
  AutomationScripts/Split Excel File/requirements.txt
  AutomationScripts/Split Excel File/split_excel_files.py
Labels: LGMSOC21, To Do, 🟩 Level1

#512 Added Pincodes of Indian City in GUIScripts
  GUIScripts/Pincodes of Indian City/Images/1.jpg
  GUIScripts/Pincodes of Indian City/Images/2.jpg
  GUIScripts/Pincodes of Indian City/Images/3.jpg
  GUIScripts/Pincodes of Indian City/Images/4.jpg
  GUIScripts/Pincodes of Indian City/Images/5.jpg
  GUIScripts/Pincodes of Indian City/Images/6.jpg
  GUIScripts/Pincodes of Indian City/Images/7.jpg
  GUIScripts/Pincodes of Indian City/Images/8.jpg
  GUIScripts/Pincodes of Indian City/Images/pincodes.gif
  GUIScripts/Pincodes of Indian City/README.md
  GUIScripts/Pincodes of Indian City/pincode_data.csv
  GUIScripts/Pincodes of Indian City/pincodes_of_indian_city.py
  GUIScripts/Pincodes of Indian City/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#388 Armstrong_number
  BasicPythonScripts/Armstrong Number/Images/armstrong_code.png
  BasicPythonScripts/Armstrong Number/Images/output1.png
  BasicPythonScripts/Armstrong Number/Images/output2.png
  BasicPythonScripts/Armstrong Number/README.md
  BasicPythonScripts/Armstrong Number/armstrong_number.py
  BasicPythonScripts/Armstrong Number/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#517 Added Highlight Selected Part of Text in GUIScripts
  GUIScripts/Highlight Selected Part of Text/Images/1.jpg
  GUIScripts/Highlight Selected Part of Text/Images/2.jpg
  GUIScripts/Highlight Selected Part of Text/Images/3.jpg
  GUIScripts/Highlight Selected Part of Text/Images/4.jpg
  GUIScripts/Highlight Selected Part of Text/Images/5.jpg
  GUIScripts/Highlight Selected Part of Text/Images/6.jpg
  GUIScripts/Highlight Selected Part of Text/README.md
  GUIScripts/Highlight Selected Part of Text/highlight_selected_part_of_text.py
  GUIScripts/Highlight Selected Part of Text/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2
