Repository prathimacode-hub/Awesome_Python_Scripts, pull requests merged in 2021-07, with the labels that each got.

#584 Facts Generator added
  BasicPythonScripts/Facts Generator/Images/Output.png
  BasicPythonScripts/Facts Generator/README.md
  BasicPythonScripts/Facts Generator/facts_generator.py
  BasicPythonScripts/Facts Generator/requirements.txt
  GUIScripts/Wikipedia Summary/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#592 Added All Camera Model Detailer in GUI Scripts
  GUIScripts/All Camera Model Detailer/Images/1.jpg
  GUIScripts/All Camera Model Detailer/Images/2.jpg
  GUIScripts/All Camera Model Detailer/Images/3.jpg
  GUIScripts/All Camera Model Detailer/Images/4.jpg
  GUIScripts/All Camera Model Detailer/Images/5.jpg
  GUIScripts/All Camera Model Detailer/Images/6.jpg
  GUIScripts/All Camera Model Detailer/Images/7.jpg
  GUIScripts/All Camera Model Detailer/Images/cameras.gif
  GUIScripts/All Camera Model Detailer/README.md
  GUIScripts/All Camera Model Detailer/all_camera_model_detailer.py
  GUIScripts/All Camera Model Detailer/camera_dataset.csv
  GUIScripts/All Camera Model Detailer/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#594 Bruteforce Attack
  BasicPythonScripts/Bruteforce Attack/Images/output_1(bruteforce).png
  BasicPythonScripts/Bruteforce Attack/Images/output_2(bruteforce).png
  BasicPythonScripts/Bruteforce Attack/README.md
  BasicPythonScripts/Bruteforce Attack/bruteforce_attack.py
  BasicPythonScripts/Bruteforce Attack/requirements.txt
Labels: LGMSOC21, To Do, 🟪 Level0

#597 added a script for quotes automation
  AutomationScripts/Quotes Automation/Images/quotes_img1.png
  AutomationScripts/Quotes Automation/Images/quotes_img2.png
  AutomationScripts/Quotes Automation/Images/quotes_img3.png
  AutomationScripts/Quotes Automation/Images/quotes_img4.png
  AutomationScripts/Quotes Automation/README.md
  AutomationScripts/Quotes Automation/quotes_automation.py
  AutomationScripts/Quotes Automation/requirements.txt
Labels: LGMSOC21, To Do, 🟪 Level0

#601 Added All Laptop Detailer in Python Scripts
  GUIScripts/All Laptop Detailer/Images/1.jpg
  GUIScripts/All Laptop Detailer/Images/2.jpg
  GUIScripts/All Laptop Detailer/Images/3.jpg
  GUIScripts/All Laptop Detailer/Images/4.jpg
  GUIScripts/All Laptop Detailer/Images/5.jpg
  GUIScripts/All Laptop Detailer/Images/6.jpg
  GUIScripts/All Laptop Detailer/Images/7.jpg
  GUIScripts/All Laptop Detailer/Images/laptops.gif
  GUIScripts/All Laptop Detailer/README.md
  GUIScripts/All Laptop Detailer/all_laptop_detailer.py
  GUIScripts/All Laptop Detailer/laptop_dataset.csv
  GUIScripts/All Laptop Detailer/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#583 Added Password Generator Game.
  BasicPythonScripts/Password Generator Game/Images/screenshot.png
  BasicPythonScripts/Password Generator Game/README.md
  BasicPythonScripts/Password Generator Game/password_generator.py
  BasicPythonScripts/Password Generator Game/requirements.txt
  PyGamesScripts/Coffee Machine Game/__pycache__/machine.cpython-39.pyc
Labels: LGMSOC21, To Do, 🟩 Level1

#605 Move Files To Creation and Modification Date Named Directories
  AutomationScripts/Manage Files Accordingly/Images/input.jpg
  AutomationScripts/Manage Files Accordingly/Images/output.jpg
  AutomationScripts/Manage Files Accordingly/README.md
  AutomationScripts/Manage Files Accordingly/manage _files_accordingly.py
  AutomationScripts/Manage Files Accordingly/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#608 Chrome Dinosaur Automation
  AutomationScripts/Chrome Dinosaur Automation/Images/output(dino).png
  AutomationScripts/Chrome Dinosaur Automation/README.md
  AutomationScripts/Chrome Dinosaur Automation/chrome_dinosaur_automation.py
  AutomationScripts/Chrome Dinosaur Automation/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#610 Added Text Editor in GUI Scripts
  GUIScripts/Text Editor/Images/1.jpg
  GUIScripts/Text Editor/Images/10.jpg
  GUIScripts/Text Editor/Images/11.jpg
  GUIScripts/Text Editor/Images/12.jpg
  GUIScripts/Text Editor/Images/2.jpg
  GUIScripts/Text Editor/Images/3.jpg
  GUIScripts/Text Editor/Images/4.jpg
  GUIScripts/Text Editor/Images/5.jpg
  GUIScripts/Text Editor/Images/6.jpg
  GUIScripts/Text Editor/Images/7.jpg
  GUIScripts/Text Editor/Images/8.jpg
  GUIScripts/Text Editor/Images/9.jpg
  GUIScripts/Text Editor/Images/about.gif
  GUIScripts/Text Editor/Images/copy.gif
  GUIScripts/Text Editor/Images/cut.gif
  GUIScripts/Text Editor/Images/new_file.gif
  GUIScripts/Text Editor/Images/newfile.gif
  GUIScripts/Text Editor/Images/on_find.gif
  GUIScripts/Text Editor/Images/onfind.gif
  GUIScripts/Text Editor/Images/open_file.gif
  GUIScripts/Text Editor/Images/openfile.gif
  GUIScripts/Text Editor/Images/paste.gif
  GUIScripts/Text Editor/Images/redo.gif
  GUIScripts/Text Editor/Images/save.gif
  GUIScripts/Text Editor/Images/undo.gif
  GUIScripts/Text Editor/README.md
  GUIScripts/Text Editor/requirements.txt
  GUIScripts/Text Editor/text_editor.py
Labels: LGMSOC21, To Do, 🟧 Level3

#607 Apple Store
  AutomationScripts/Apple Store/Images/front_page.jpg
  AutomationScripts/Apple Store/Images/login_page.jpg
  AutomationScripts/Apple Store/Images/market_page.jpg
  AutomationScripts/Apple Store/Images/purchase_item.jpg
  AutomationScripts/Apple Store/Images/register_page.jpg
  AutomationScripts/Apple Store/Images/transaction.jpg
  AutomationScripts/Apple Store/Market/__init__.py
  AutomationScripts/Apple Store/Market/forms.py
  AutomationScripts/Apple Store/Market/market.db
  AutomationScripts/Apple Store/Market/models.py
  AutomationScripts/Apple Store/Market/routes.py
  AutomationScripts/Apple Store/Market/templates/base.html
  AutomationScripts/Apple Store/Market/templates/home.html
  AutomationScripts/Apple Store/Market/templates/includes/items_modals.html
  AutomationScripts/Apple Store/Market/templates/includes/owned_items_modals.html
  AutomationScripts/Apple Store/Market/templates/login.html
  AutomationScripts/Apple Store/Market/templates/market.html
  AutomationScripts/Apple Store/Market/templates/register.html
  AutomationScripts/Apple Store/README.md
  AutomationScripts/Apple Store/run.py
  BasicPythonScripts/Multiple Choice Questions/Images/README.md
Labels: LGMSOC21, To Do, 🟥 Level4

#611 Fibonacci Series Generator
  BasicPythonScripts/Fibonacci Sequence Generator/Images/Fib_ouput1.png
  BasicPythonScripts/Fibonacci Sequence Generator/Images/Fib_ouput2.png
  BasicPythonScripts/Fibonacci Sequence Generator/Images/Fib_ouput3.png
  BasicPythonScripts/Fibonacci Sequence Generator/Images/fibonacci_ series_code.png
  BasicPythonScripts/Fibonacci Sequence Generator/README.md
  BasicPythonScripts/Fibonacci Sequence Generator/fibonacci_sequence_generator.py
  BasicPythonScripts/Fibonacci Sequence Generator/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#614 Image Displayer GUI
  GUIScripts/Image Displayer GUI/Image_displayer_gui.py
  GUIScripts/Image Displayer GUI/Images/output_1(image).png
  GUIScripts/Image Displayer GUI/Images/output_2(image).png
  GUIScripts/Image Displayer GUI/Images/output_3(image).png
  GUIScripts/Image Displayer GUI/README.md
  GUIScripts/Image Displayer GUI/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#619 Added Restaurant Management System in GUIScripts
  GUIScripts/Restaurant Management System/Images/1.jpg
  GUIScripts/Restaurant Management System/Images/2.jpg
  GUIScripts/Restaurant Management System/Images/3.jpg
  GUIScripts/Restaurant Management System/Images/4.jpg
  GUIScripts/Restaurant Management System/Images/5.jpg
  GUIScripts/Restaurant Management System/Images/6.jpg
  GUIScripts/Restaurant Management System/Images/7.jpg
  GUIScripts/Restaurant Management System/Images/8.jpg
  GUIScripts/Restaurant Management System/Images/9.jpg
  GUIScripts/Restaurant Management System/README.md
  GUIScripts/Restaurant Management System/requirements.txt
  GUIScripts/Restaurant Management System/restaurant_management_system.py
Labels: LGMSOC21, To Do, 🟨 Level2

#603 Star Pattern
  BasicPythonScripts/Star Pattern/Media/22-33-00.mp4
  BasicPythonScripts/Star Pattern/Media/Star_pattern.png
  BasicPythonScripts/Star Pattern/README.md
  BasicPythonScripts/Star Pattern/requirements.txt
  BasicPythonScripts/Star Pattern/star.py
Labels: LGMSOC21, To Do, 🟩 Level1

#625 Gesture Pet (fun Game)
  GUIScripts/Gesture Pet/Images/output(gesture_happy).png
  GUIScripts/Gesture Pet/Images/output(gesture_naughty).png
  GUIScripts/Gesture Pet/Images/output(gesture_nothing).png
  GUIScripts/Gesture Pet/Images/output(gesture_sad).png
  GUIScripts/Gesture Pet/README.md
  GUIScripts/Gesture Pet/gesture_pet.py
  GUIScripts/Gesture Pet/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#627 Added Piano Application in GUI Scripts
  GUIScripts/Piano Application/Images/1.jpg
  GUIScripts/Piano Application/Images/2.jpg
  GUIScripts/Piano Application/Images/3.jpg
  GUIScripts/Piano Application/Images/piano.jpg
  GUIScripts/Piano Application/README.md
  GUIScripts/Piano Application/Sounds/Piano1.mp3
  GUIScripts/Piano Application/Sounds/Piano10.mp3
  GUIScripts/Piano Application/Sounds/Piano11.mp3
  GUIScripts/Piano Application/Sounds/Piano12.mp3
  GUIScripts/Piano Application/Sounds/Piano13.mp3
  GUIScripts/Piano Application/Sounds/Piano14.mp3
  GUIScripts/Piano Application/Sounds/Piano15.mp3
  GUIScripts/Piano Application/Sounds/Piano16.mp3
  GUIScripts/Piano Application/Sounds/Piano17.mp3
  GUIScripts/Piano Application/Sounds/Piano18.mp3
  GUIScripts/Piano Application/Sounds/Piano19.mp3
  GUIScripts/Piano Application/Sounds/Piano2.mp3
  GUIScripts/Piano Application/Sounds/Piano20.mp3
  GUIScripts/Piano Application/Sounds/Piano21.mp3
  GUIScripts/Piano Application/Sounds/Piano22.mp3
  GUIScripts/Piano Application/Sounds/Piano23.mp3
  GUIScripts/Piano Application/Sounds/Piano3.mp3
  GUIScripts/Piano Application/Sounds/Piano4.mp3
  GUIScripts/Piano Application/Sounds/Piano5.mp3
  GUIScripts/Piano Application/Sounds/Piano6.mp3
  GUIScripts/Piano Application/Sounds/Piano7.mp3
  GUIScripts/Piano Application/Sounds/Piano8.mp3
  GUIScripts/Piano Application/Sounds/Piano9.mp3
  GUIScripts/Piano Application/piano_application.py
  GUIScripts/Piano Application/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#632 Indian Flag
  BasicPythonScripts/Indian Flag/Media/22-09-00.mp4
  BasicPythonScripts/Indian Flag/Media/flag.png
  BasicPythonScripts/Indian Flag/README.md
  BasicPythonScripts/Indian Flag/flag.py
  BasicPythonScripts/Indian Flag/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#639 Next Episode Fetcher (TV Series)
  WebScrapingScripts/Next Episode Fetcher (TV Series)/Images/output_1(episode).png
  WebScrapingScripts/Next Episode Fetcher (TV Series)/Images/output_2(episode).png
  WebScrapingScripts/Next Episode Fetcher (TV Series)/Images/output_3(episode).png
  WebScrapingScripts/Next Episode Fetcher (TV Series)/Images/output_4(episode).png
  WebScrapingScripts/Next Episode Fetcher (TV Series)/README.md
  WebScrapingScripts/Next Episode Fetcher (TV Series)/next_episode_fetcher.py
  WebScrapingScripts/Next Episode Fetcher (TV Series)/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#645 Enhanced Alarm Clock
  BasicPythonScripts/Alarm Clock/Images/new_screenshot.png
  BasicPythonScripts/Alarm Clock/README_enhanced.md
  BasicPythonScripts/Alarm Clock/Related/wake_up.mp3
  BasicPythonScripts/Alarm Clock/alarm_clock.py
  BasicPythonScripts/Alarm Clock/requirements.txt
Labels: LGMSOC21, To Do, enhancement, 🟩 Level1

#650 Added Mouse Pointer Co-ordinates Getter in GUIScripts
  GUIScripts/Mouse Pointer Co-ordinates Getter/Images/1.jpg
  GUIScripts/Mouse Pointer Co-ordinates Getter/Images/2.jpg
  GUIScripts/Mouse Pointer Co-ordinates Getter/Images/3.jpg
  GUIScripts/Mouse Pointer Co-ordinates Getter/Images/4.jpg
  GUIScripts/Mouse Pointer Co-ordinates Getter/Images/5.jpg
  GUIScripts/Mouse Pointer Co-ordinates Getter/Images/6.jpg
  GUIScripts/Mouse Pointer Co-ordinates Getter/README.md
  GUIScripts/Mouse Pointer Co-ordinates Getter/mouse_pointer_co-ordinates_getter.py
  GUIScripts/Mouse Pointer Co-ordinates Getter/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#652 Added Nutritional Calorie Recorder in GUIScripts
  GUIScripts/Nutritional Calorie Recorder/CalorieRecorder.db
  GUIScripts/Nutritional Calorie Recorder/Images/1.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/2.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/3.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/4.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/5.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/6.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/7.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/8.jpg
  GUIScripts/Nutritional Calorie Recorder/Images/calorie.jpg
  GUIScripts/Nutritional Calorie Recorder/README.md
  GUIScripts/Nutritional Calorie Recorder/nutritional_calorie_recorder.py
  GUIScripts/Nutritional Calorie Recorder/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#647 Hotel Billing System
  BasicPythonScripts/Hotel Billing System/Images/output(bill).png
  BasicPythonScripts/Hotel Billing System/README.md
  BasicPythonScripts/Hotel Billing System/hotel_billing_system.py
  BasicPythonScripts/Hotel Billing System/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#655 Unit Converter GUI
  GUIScripts/Unit Converter GUI/Images/README.md
  GUIScripts/Unit Converter GUI/Images/output_1(unit).png
  GUIScripts/Unit Converter GUI/Images/output_2(unit).png
  GUIScripts/Unit Converter GUI/README.md
  GUIScripts/Unit Converter GUI/requirements.txt
  GUIScripts/Unit Converter GUI/unit_converter_gui.py
Labels: LGMSOC21, To Do, 🟩 Level1

#662 Github Bot
  AutomationScripts/Github Bot/Images/output_1(git).png
  AutomationScripts/Github Bot/Images/output_2(git).png
  AutomationScripts/Github Bot/Images/output_3(git).png
  AutomationScripts/Github Bot/README.md
  AutomationScripts/Github Bot/github_bot.py
  AutomationScripts/Github Bot/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#663 Added Image Resizer in ImageProcessing Scripts
  ImageProcessingScripts/Image Resizer/Images/1.jpg
  ImageProcessingScripts/Image Resizer/Images/2.jpg
  ImageProcessingScripts/Image Resizer/Images/3.jpg
  ImageProcessingScripts/Image Resizer/Images/4.jpg
  ImageProcessingScripts/Image Resizer/Images/5.jpg
  ImageProcessingScripts/Image Resizer/Images/6.jpg
  ImageProcessingScripts/Image Resizer/Images/7.jpg
  ImageProcessingScripts/Image Resizer/Images/8.jpg
  ImageProcessingScripts/Image Resizer/Images/9.jpg
  ImageProcessingScripts/Image Resizer/README.md
  ImageProcessingScripts/Image Resizer/image_resizer.py
  ImageProcessingScripts/Image Resizer/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#656 I love you in python
  GUIScripts/Message- I Love You/Images/end.png
  GUIScripts/Message- I Love You/Images/initial.png
  GUIScripts/Message- I Love You/Images/screen-capture (11) (1).gif
  GUIScripts/Message- I Love You/README.md
  GUIScripts/Message- I Love You/love.py
Labels: LGMSOC21, To Do, 🟩 Level1

#666 Image Cartoonifier
  ImageProcessingScripts/Image Cartoonfier/Images/image.jpg
  ImageProcessingScripts/Image Cartoonfier/Images/output(cartoon).png
  ImageProcessingScripts/Image Cartoonfier/README.md
  ImageProcessingScripts/Image Cartoonfier/image_cartoonifier.py
  ImageProcessingScripts/Image Cartoonfier/requirements.txt
Labels: LGMSOC21, To Do, 🟪 Level0

#661 Base convertering
  BasicPythonScripts/Base Converter/Images/01.png
  BasicPythonScripts/Base Converter/Images/02.png
  BasicPythonScripts/Base Converter/Images/03.png
  BasicPythonScripts/Base Converter/README.md
  BasicPythonScripts/Base Converter/base_converter.py
  BasicPythonScripts/Base Converter/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#669 Added MP4 To MP3 Converter in GUIScripts
  GUIScripts/MP4 To MP3 Converter/Images/1.jpg
  GUIScripts/MP4 To MP3 Converter/Images/2.jpg
  GUIScripts/MP4 To MP3 Converter/Images/3.jpg
  GUIScripts/MP4 To MP3 Converter/Images/4.jpg
  GUIScripts/MP4 To MP3 Converter/Images/5.jpg
  GUIScripts/MP4 To MP3 Converter/Images/6.jpg
  GUIScripts/MP4 To MP3 Converter/Images/convert.jpg
  GUIScripts/MP4 To MP3 Converter/README.md
  GUIScripts/MP4 To MP3 Converter/mp4_to_mp3_converter.py
  GUIScripts/MP4 To MP3 Converter/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#668 Adding code for heart shape
  BasicPythonScripts/Heart Shape/Media/21-25-10.mp4
  BasicPythonScripts/Heart Shape/Media/Heart.png
  BasicPythonScripts/Heart Shape/Media/README.md
  BasicPythonScripts/Heart Shape/Media/requirements.txt
  BasicPythonScripts/Heart Shape/heart.py
Labels: LGMSOC21, To Do, 🟪 Level0

#653 Reddit Video Downloader
  WebScrapingScripts/Reddit Video Downloader/Images/output.png
  WebScrapingScripts/Reddit Video Downloader/README.md
  WebScrapingScripts/Reddit Video Downloader/Reddit_Video_Downloader.py
  WebScrapingScripts/Reddit Video Downloader/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#673 University Website
  GUIScripts/University Website/Images/attendance.jpg
  GUIScripts/University Website/Images/course.jpg
  GUIScripts/University Website/Images/details.jpg
  GUIScripts/University Website/Images/fees.jpg
  GUIScripts/University Website/Images/front_page.jpg
  GUIScripts/University Website/Images/login_page.jpg
  GUIScripts/University Website/Images/result.jpg
  GUIScripts/University Website/Images/time_table.jpg
  GUIScripts/University Website/README.md
  GUIScripts/University Website/application.py
  GUIScripts/University Website/forms.py
  GUIScripts/University Website/routes.py
  GUIScripts/University Website/student.sqlite3
  GUIScripts/University Website/templates/attendance.html
  GUIScripts/University Website/templates/course.html
  GUIScripts/University Website/templates/details.html
  GUIScripts/University Website/templates/fees.html
  GUIScripts/University Website/templates/home.html
  GUIScripts/University Website/templates/login.html
  GUIScripts/University Website/templates/register.html
  GUIScripts/University Website/templates/result.html
  GUIScripts/University Website/templates/time_table.html
Labels: LGMSOC21, 🟥 Level4

#675 Added EMI Calculator in GUIScripts
  GUIScripts/EMI Calculator/EMI_calculator.py
  GUIScripts/EMI Calculator/Images/1.jpg
  GUIScripts/EMI Calculator/Images/10.jpg
  GUIScripts/EMI Calculator/Images/2.jpg
  GUIScripts/EMI Calculator/Images/3.jpg
  GUIScripts/EMI Calculator/Images/4.jpg
  GUIScripts/EMI Calculator/Images/5.jpg
  GUIScripts/EMI Calculator/Images/6.jpg
  GUIScripts/EMI Calculator/Images/7.jpg
  GUIScripts/EMI Calculator/Images/8.jpg
  GUIScripts/EMI Calculator/Images/9.jpg
  GUIScripts/EMI Calculator/Images/EMI_pdf.png
  GUIScripts/EMI Calculator/Images/emi_front.jpg
  GUIScripts/EMI Calculator/README.md
  GUIScripts/EMI Calculator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#677 Added Screenshot Taker in GUIScripts
  GUIScripts/Screenshot Taker/Images/1.jpg
  GUIScripts/Screenshot Taker/Images/2.jpg
  GUIScripts/Screenshot Taker/Images/3.jpg
  GUIScripts/Screenshot Taker/Images/4.jpg
  GUIScripts/Screenshot Taker/Images/5.jpg
  GUIScripts/Screenshot Taker/Images/6.jpg
  GUIScripts/Screenshot Taker/Images/7.jpg
  GUIScripts/Screenshot Taker/Images/8.jpg
  GUIScripts/Screenshot Taker/README.md
  GUIScripts/Screenshot Taker/requirements.txt
  GUIScripts/Screenshot Taker/screenshot_taker.py
Labels: LGMSOC21, To Do, 🟩 Level1

#680 Added URL Extractor in GUIScripts
  GUIScripts/URL Extractor/Images/1.jpg
  GUIScripts/URL Extractor/Images/2.jpg
  GUIScripts/URL Extractor/Images/3.jpg
  GUIScripts/URL Extractor/Images/4.jpg
  GUIScripts/URL Extractor/Images/5.jpg
  GUIScripts/URL Extractor/Images/6.jpg
  GUIScripts/URL Extractor/README.md
  GUIScripts/URL Extractor/requirements.txt
  GUIScripts/URL Extractor/url_extractor.py
Labels: LGMSOC21, To Do, 🟨 Level2

#682 Added Programming Language Detector in GUIScripts
  GUIScripts/Programming Language Detector/Images/1.jpg
  GUIScripts/Programming Language Detector/Images/10.jpg
  GUIScripts/Programming Language Detector/Images/2.jpg
  GUIScripts/Programming Language Detector/Images/3.jpg
  GUIScripts/Programming Language Detector/Images/4.jpg
  GUIScripts/Programming Language Detector/Images/5.jpg
  GUIScripts/Programming Language Detector/Images/6.jpg
  GUIScripts/Programming Language Detector/Images/7.jpg
  GUIScripts/Programming Language Detector/Images/8.jpg
  GUIScripts/Programming Language Detector/Images/9.jpg
  GUIScripts/Programming Language Detector/README.md
  GUIScripts/Programming Language Detector/programming_language_detector.py
  GUIScripts/Programming Language Detector/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#684 Added Latitude-Longitude Pair Verifier in GUIScripts
  GUIScripts/Latitude-Longitude Pair Verifier/Images/1.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/10.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/2.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/3.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/4.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/5.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/6.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/7.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/8.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/9.jpg
  GUIScripts/Latitude-Longitude Pair Verifier/Images/latlong.gif
  GUIScripts/Latitude-Longitude Pair Verifier/README.md
  GUIScripts/Latitude-Longitude Pair Verifier/latitude-longitude_pair_verifier.py
  GUIScripts/Latitude-Longitude Pair Verifier/requirements.txt
  GUIScripts/Latitude-Longitude Pair Verifier/world_location.csv
Labels: LGMSOC21, To Do, 🟨 Level2

#687 Added IP Address Extractor-Validator in GUIScripts
  GUIScripts/IP Address Extractor-Validator/IP_address_extractor-validator.py
  GUIScripts/IP Address Extractor-Validator/Images/1.jpg
  GUIScripts/IP Address Extractor-Validator/Images/10.jpg
  GUIScripts/IP Address Extractor-Validator/Images/11.jpg
  GUIScripts/IP Address Extractor-Validator/Images/12.jpg
  GUIScripts/IP Address Extractor-Validator/Images/13.jpg
  GUIScripts/IP Address Extractor-Validator/Images/2.jpg
  GUIScripts/IP Address Extractor-Validator/Images/3.jpg
  GUIScripts/IP Address Extractor-Validator/Images/4.jpg
  GUIScripts/IP Address Extractor-Validator/Images/5.jpg
  GUIScripts/IP Address Extractor-Validator/Images/6.jpg
  GUIScripts/IP Address Extractor-Validator/Images/7.jpg
  GUIScripts/IP Address Extractor-Validator/Images/8.jpg
  GUIScripts/IP Address Extractor-Validator/Images/9.jpg
  GUIScripts/IP Address Extractor-Validator/Images/front_ip.jpg
  GUIScripts/IP Address Extractor-Validator/Images/one.gif
  GUIScripts/IP Address Extractor-Validator/README.md
  GUIScripts/IP Address Extractor-Validator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#689 To Do List
  GUIScripts/To Do List/Images/Image-1.jpg
  GUIScripts/To Do List/Images/Image-2.jpg
  GUIScripts/To Do List/README.md
  GUIScripts/To Do List/requirements.txt
  GUIScripts/To Do List/to_do_list.py
Labels: LGMSOC21, To Do, 🟨 Level2

#696 Added Absolute Time Delta in GUIScripts
  GUIScripts/Absolute Time Delta/Images/1.jpg
  GUIScripts/Absolute Time Delta/Images/2.jpg
  GUIScripts/Absolute Time Delta/Images/3.jpg
  GUIScripts/Absolute Time Delta/Images/4.jpg
  GUIScripts/Absolute Time Delta/Images/5.jpg
  GUIScripts/Absolute Time Delta/Images/6.jpg
  GUIScripts/Absolute Time Delta/Images/7.jpg
  GUIScripts/Absolute Time Delta/Images/8.jpg
  GUIScripts/Absolute Time Delta/README.md
  GUIScripts/Absolute Time Delta/absolute_time_delta.py
  GUIScripts/Absolute Time Delta/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#695 Added Code For KhataBook Script
  GUIScripts/Khata Book Management System/Images/KhataAdding.jpg
  GUIScripts/Khata Book Management System/Images/Showcust.jpg
  GUIScripts/Khata Book Management System/Images/khata.jpg
  GUIScripts/Khata Book Management System/Images/showall.jpg
  GUIScripts/Khata Book Management System/README.md
  GUIScripts/Khata Book Management System/khata_book.py
  GUIScripts/Khata Book Management System/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#698 Added Hex Color Code in GUIScripts
  GUIScripts/Hex Color Code/Images/1.jpg
  GUIScripts/Hex Color Code/Images/2.jpg
  GUIScripts/Hex Color Code/Images/3.jpg
  GUIScripts/Hex Color Code/Images/4.jpg
  GUIScripts/Hex Color Code/Images/5.jpg
  GUIScripts/Hex Color Code/Images/6.jpg
  GUIScripts/Hex Color Code/Images/7.jpg
  GUIScripts/Hex Color Code/README.md
  GUIScripts/Hex Color Code/hex_color_code.py
  GUIScripts/Hex Color Code/hex_data.csv
  GUIScripts/Hex Color Code/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#708 Added Postal Code Validator in GUIScripts
  GUIScripts/Postal Code Validator/Images/1.jpg
  GUIScripts/Postal Code Validator/Images/10.jpg
  GUIScripts/Postal Code Validator/Images/2.jpg
  GUIScripts/Postal Code Validator/Images/3.jpg
  GUIScripts/Postal Code Validator/Images/4.jpg
  GUIScripts/Postal Code Validator/Images/5.jpg
  GUIScripts/Postal Code Validator/Images/6.jpg
  GUIScripts/Postal Code Validator/Images/7.jpg
  GUIScripts/Postal Code Validator/Images/8.jpg
  GUIScripts/Postal Code Validator/Images/9.jpg
  GUIScripts/Postal Code Validator/Images/postal_code1.jpg
  GUIScripts/Postal Code Validator/README.md
  GUIScripts/Postal Code Validator/pincode_data.csv
  GUIScripts/Postal Code Validator/postal_code_validator.py
  GUIScripts/Postal Code Validator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#703 Hotel Management System
  GUIScripts/Hotel Management System/Code/checkin_gui.py
  GUIScripts/Hotel Management System/Code/checkout_gui.py
  GUIScripts/Hotel Management System/Code/getinfo_gui.py
  GUIScripts/Hotel Management System/Code/list_gui.py
  GUIScripts/Hotel Management System/Code/main.py
  GUIScripts/Hotel Management System/Code/mainly.py
  GUIScripts/Hotel Management System/Code/recipt.py
  GUIScripts/Hotel Management System/Images/Image-1.png
  GUIScripts/Hotel Management System/Images/Image-2.png
  GUIScripts/Hotel Management System/Images/Image-3.png
  GUIScripts/Hotel Management System/Images/Image-4.png
  GUIScripts/Hotel Management System/Images/Image-5.png
  GUIScripts/Hotel Management System/Images/Image-6.png
  GUIScripts/Hotel Management System/README.md
  GUIScripts/Hotel Management System/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#716 Pharmacy Management System
  GUIScripts/Pharmacy Management System/Database/database_proj
  GUIScripts/Pharmacy Management System/Database/database_proj1
  GUIScripts/Pharmacy Management System/Images/Image-1.png
  GUIScripts/Pharmacy Management System/Images/Image-2.png
  GUIScripts/Pharmacy Management System/Images/Image-3.png
  GUIScripts/Pharmacy Management System/Images/Image-4.png
  GUIScripts/Pharmacy Management System/README.md
  GUIScripts/Pharmacy Management System/pharmacy_management_system.py
  GUIScripts/Pharmacy Management System/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#715 Loan Calculator
  GUIScripts/Loan Calculator/Images/output_1(loan).png
  GUIScripts/Loan Calculator/Images/output_2(loan).png
  GUIScripts/Loan Calculator/README.md
  GUIScripts/Loan Calculator/loan_calculator.py
  GUIScripts/Loan Calculator/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#711 Drink Water Reminder Python Script
  BasicPythonScripts/Drink Water Reminder/Images/Screenshot (365).png
  BasicPythonScripts/Drink Water Reminder/README.md
  BasicPythonScripts/Drink Water Reminder/Related files/glassicon.ico
  BasicPythonScripts/Drink Water Reminder/drink_water.py
  BasicPythonScripts/Drink Water Reminder/requirements.txt
Labels: DCP21, 🟪 Level0

#718 Added Code Comments Fetcher in GUIScripts
  GUIScripts/Code Comments Fetcher/Images/1.jpg
  GUIScripts/Code Comments Fetcher/Images/10.jpg
  GUIScripts/Code Comments Fetcher/Images/2.jpg
  GUIScripts/Code Comments Fetcher/Images/3.jpg
  GUIScripts/Code Comments Fetcher/Images/4.jpg
  GUIScripts/Code Comments Fetcher/Images/5.jpg
  GUIScripts/Code Comments Fetcher/Images/6.jpg
  GUIScripts/Code Comments Fetcher/Images/7.jpg
  GUIScripts/Code Comments Fetcher/Images/8.jpg
  GUIScripts/Code Comments Fetcher/Images/9.jpg
  GUIScripts/Code Comments Fetcher/README.md
  GUIScripts/Code Comments Fetcher/code_comments_fetcher.py
  GUIScripts/Code Comments Fetcher/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#721 Contact Management System
  GUIScripts/Contact Management System/Images/Image-1.png
  GUIScripts/Contact Management System/Images/Image-2.png
  GUIScripts/Contact Management System/Images/Image-3.png
  GUIScripts/Contact Management System/README.md
  GUIScripts/Contact Management System/contact_management_system.py
  GUIScripts/Contact Management System/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#726 Added Color Converter in GUIScripts
  GUIScripts/Color Converter/Images/1.jpg
  GUIScripts/Color Converter/Images/10.jpg
  GUIScripts/Color Converter/Images/2.jpg
  GUIScripts/Color Converter/Images/3.jpg
  GUIScripts/Color Converter/Images/4.jpg
  GUIScripts/Color Converter/Images/5.jpg
  GUIScripts/Color Converter/Images/6.jpg
  GUIScripts/Color Converter/Images/7.jpg
  GUIScripts/Color Converter/Images/8.jpg
  GUIScripts/Color Converter/Images/9.jpg
  GUIScripts/Color Converter/Images/color.png
  GUIScripts/Color Converter/README.md
  GUIScripts/Color Converter/color_converter.py
  GUIScripts/Color Converter/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#729 Slide Game
  PyGamesScripts/Sliding Game/Images/Image-1.png
  PyGamesScripts/Sliding Game/Images/Image-2.png
  PyGamesScripts/Sliding Game/README.md
  PyGamesScripts/Sliding Game/requirements.txt
  PyGamesScripts/Sliding Game/sliding_game.py
Labels: LGMSOC21, To Do, 🟧 Level3

#731 Added Resume Generator in GUIScripts
  GUIScripts/Resume Generator/Images/1.jpg
  GUIScripts/Resume Generator/Images/10.jpg
  GUIScripts/Resume Generator/Images/11.jpg
  GUIScripts/Resume Generator/Images/12.jpg
  GUIScripts/Resume Generator/Images/13.jpg
  GUIScripts/Resume Generator/Images/14.jpg
  GUIScripts/Resume Generator/Images/2.jpg
  GUIScripts/Resume Generator/Images/3.jpg
  GUIScripts/Resume Generator/Images/4.jpg
  GUIScripts/Resume Generator/Images/5.jpg
  GUIScripts/Resume Generator/Images/6.jpg
  GUIScripts/Resume Generator/Images/7.jpg
  GUIScripts/Resume Generator/Images/8.jpg
  GUIScripts/Resume Generator/Images/9.jpg
  GUIScripts/Resume Generator/Images/My_Resume1.png
  GUIScripts/Resume Generator/Images/resume_front.png
  GUIScripts/Resume Generator/README.md
  GUIScripts/Resume Generator/requirements.txt
  GUIScripts/Resume Generator/resume_generator.py
Labels: LGMSOC21, To Do, 🟧 Level3

#734 Analog Clock
  GUIScripts/Analog Clock/Images/Image-1.png
  GUIScripts/Analog Clock/README.md
  GUIScripts/Analog Clock/analog_clock.py
  GUIScripts/Analog Clock/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#737 Added Regex Checker in GUIScripts
  GUIScripts/Regex Checker/Images/1.jpg
  GUIScripts/Regex Checker/Images/2.jpg
  GUIScripts/Regex Checker/Images/3.jpg
  GUIScripts/Regex Checker/Images/4.jpg
  GUIScripts/Regex Checker/Images/5.jpg
  GUIScripts/Regex Checker/Images/6.jpg
  GUIScripts/Regex Checker/Images/7.jpg
  GUIScripts/Regex Checker/Images/regex.gif
  GUIScripts/Regex Checker/README.md
  GUIScripts/Regex Checker/regex_checker.py
  GUIScripts/Regex Checker/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#739 Simulate Color Game
  PyGamesScripts/Simulate Color Game/Images/Image-1.png
  PyGamesScripts/Simulate Color Game/Images/Image-2.png
  PyGamesScripts/Simulate Color Game/README.md
  PyGamesScripts/Simulate Color Game/Sound/beep1.ogg
  PyGamesScripts/Simulate Color Game/Sound/beep2.ogg
  PyGamesScripts/Simulate Color Game/Sound/beep3.ogg
  PyGamesScripts/Simulate Color Game/Sound/beep4.ogg
  PyGamesScripts/Simulate Color Game/requirements.txt
  PyGamesScripts/Simulate Color Game/simulate_color_game.py
Labels: LGMSOC21, 🟨 Level2

#738 Marvel API
  APIScripts/Marvel API/Images/output_1(marvel).png
  APIScripts/Marvel API/Images/output_2(marvel).png
  APIScripts/Marvel API/README.md
  APIScripts/Marvel API/marvel_api.py
  APIScripts/Marvel API/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#742 Added Sentence Segmenter in GUIScripts
  GUIScripts/Sentence Segmenter/Images/1.jpg
  GUIScripts/Sentence Segmenter/Images/2.jpg
  GUIScripts/Sentence Segmenter/Images/3.jpg
  GUIScripts/Sentence Segmenter/Images/4.jpg
  GUIScripts/Sentence Segmenter/Images/5.jpg
  GUIScripts/Sentence Segmenter/Images/6.jpg
  GUIScripts/Sentence Segmenter/Images/7.jpg
  GUIScripts/Sentence Segmenter/README.md
  GUIScripts/Sentence Segmenter/requirements.txt
  GUIScripts/Sentence Segmenter/sentence_segmenter.py
Labels: LGMSOC21, To Do, 🟨 Level2

#747 Added Credit Card Number Authentication in GUIScripts
  GUIScripts/Credit Card Numbers Authentication/Images/1.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/2.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/3.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/4.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/5.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/6.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/7.jpg
  GUIScripts/Credit Card Numbers Authentication/Images/card.gif
  GUIScripts/Credit Card Numbers Authentication/README.md
  GUIScripts/Credit Card Numbers Authentication/credit_card_numbers_authentication.py
  GUIScripts/Credit Card Numbers Authentication/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#744 Tetromino Game
  PyGamesScripts/Tetromino Game/Images/Image-1.png
  PyGamesScripts/Tetromino Game/Images/Image-2.png
  PyGamesScripts/Tetromino Game/Images/Image-3.png
  PyGamesScripts/Tetromino Game/README.md
  PyGamesScripts/Tetromino Game/Sound/tetrisb.mid
  PyGamesScripts/Tetromino Game/Sound/tetrisc.mid
  PyGamesScripts/Tetromino Game/requirements.txt
  PyGamesScripts/Tetromino Game/tetromino_game.py
Labels: LGMSOC21, To Do, 🟧 Level3

#732 Added Enhanced Version of Registration Form using Tkinter
  GUIScripts/Registration Form/Enhanced/Images/1.png
  GUIScripts/Registration Form/Enhanced/Images/2.png
  GUIScripts/Registration Form/Enhanced/Images/msgbox.png
  GUIScripts/Registration Form/Enhanced/Images/sql.png
  GUIScripts/Registration Form/Enhanced/Images/text
  GUIScripts/Registration Form/Enhanced/README.md
  GUIScripts/Registration Form/Enhanced/Related/registration_form.py
  GUIScripts/Registration Form/Enhanced/Related/theja.db
  GUIScripts/Registration Form/Enhanced/registration_form.ipynb
  GUIScripts/Registration Form/Enhanced/requirements.txt
Labels: DCP21, 🟨 Level2

#727 ADDED CODE FOR MEMORY_PUZZLE_GAME (ISSUE-231)
  PyGamesScripts/Memory Puzzle Game/Images/chicken.png
  PyGamesScripts/Memory Puzzle Game/Images/cow.png
  PyGamesScripts/Memory Puzzle Game/Images/dog.png
  PyGamesScripts/Memory Puzzle Game/Images/duck.png
  PyGamesScripts/Memory Puzzle Game/Images/elephant.png
  PyGamesScripts/Memory Puzzle Game/Images/giraffe.png
  PyGamesScripts/Memory Puzzle Game/Images/hippo.png
  PyGamesScripts/Memory Puzzle Game/Images/matched.png
  PyGamesScripts/Memory Puzzle Game/Images/output_1.jpg
  PyGamesScripts/Memory Puzzle Game/Images/output_2.jpg
  PyGamesScripts/Memory Puzzle Game/Images/output_3.jpg
  PyGamesScripts/Memory Puzzle Game/Images/output_4.jpg
  PyGamesScripts/Memory Puzzle Game/Images/panda.png
  PyGamesScripts/Memory Puzzle Game/README.md
  PyGamesScripts/Memory Puzzle Game/animal.py
  PyGamesScripts/Memory Puzzle Game/app.py
  PyGamesScripts/Memory Puzzle Game/game_config.py
  PyGamesScripts/Memory Puzzle Game/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#746 Collison detection
  PyGamesScripts/Collision Detection/Images/output1.png
  PyGamesScripts/Collision Detection/Images/output2.png
  PyGamesScripts/Collision Detection/Images/readme.txt
  PyGamesScripts/Collision Detection/README.md
  PyGamesScripts/Collision Detection/Related/myMethods.py
  PyGamesScripts/Collision Detection/collision_detection.py
  PyGamesScripts/Collision Detection/requirements.txt
Labels: DCP21, 🟨 Level2

#754 Added Smart Calculator
  GUIScripts/Smart Calculator/Images/smart_calculator1.jpg
  GUIScripts/Smart Calculator/Images/smart_calculator2.jpg
  GUIScripts/Smart Calculator/README.md
  GUIScripts/Smart Calculator/requirements.txt
  GUIScripts/Smart Calculator/smart_calculator.py
Labels: DCP21, 🟩 Level1

#755 Added Age On Different Planet in GUIScript
  GUIScripts/Age On Different Planet/Images/1.jpg
  GUIScripts/Age On Different Planet/Images/10.jpg
  GUIScripts/Age On Different Planet/Images/2.jpg
  GUIScripts/Age On Different Planet/Images/3.jpg
  GUIScripts/Age On Different Planet/Images/4.jpg
  GUIScripts/Age On Different Planet/Images/5.jpg
  GUIScripts/Age On Different Planet/Images/6.jpg
  GUIScripts/Age On Different Planet/Images/7.jpg
  GUIScripts/Age On Different Planet/Images/8.jpg
  GUIScripts/Age On Different Planet/Images/9.jpg
  GUIScripts/Age On Different Planet/Images/Age On Different Planet - Shortcut.lnk
  GUIScripts/Age On Different Planet/Images/age.jpg
  GUIScripts/Age On Different Planet/Images/earth.gif
  GUIScripts/Age On Different Planet/Images/jupiter.gif
  GUIScripts/Age On Different Planet/Images/mars.gif
  GUIScripts/Age On Different Planet/Images/mercury.gif
  GUIScripts/Age On Different Planet/Images/neptune.gif
  GUIScripts/Age On Different Planet/Images/pluto.gif
  GUIScripts/Age On Different Planet/Images/saturn.gif
  GUIScripts/Age On Different Planet/Images/sun.gif
  GUIScripts/Age On Different Planet/Images/uranus.gif
  GUIScripts/Age On Different Planet/Images/venus.gif
  GUIScripts/Age On Different Planet/README.md
  GUIScripts/Age On Different Planet/age_on_different_planet.py
  GUIScripts/Age On Different Planet/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#757 Enhanced - Snake and Ladder Game
  PyGamesScripts/Snakes and Ladders Game/Enhanced/Images/Image-1.png
  PyGamesScripts/Snakes and Ladders Game/Enhanced/Images/Image-2.png
  PyGamesScripts/Snakes and Ladders Game/Enhanced/Images/Image-3.png
  PyGamesScripts/Snakes and Ladders Game/Enhanced/Images/Image-4.png
  PyGamesScripts/Snakes and Ladders Game/Enhanced/README.md
  PyGamesScripts/Snakes and Ladders Game/Enhanced/requirements.txt
  PyGamesScripts/Snakes and Ladders Game/Enhanced/snake_and_ladder.py
Labels: LGMSOC21, 🟨 Level2

#760 Star Pusher Game
  PyGamesScripts/Star - Pusher Game/Images/Background/Grass_Block.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Plain_Block.png
  PyGamesScripts/Star - Pusher Game/Images/Background/RedSelector.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Rock.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Selector.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Star.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Tree_Short.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Tree_Tall.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Tree_Ugly.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Wall_Block_Tall.png
  PyGamesScripts/Star - Pusher Game/Images/Background/Wood_Block_Tall.png
  PyGamesScripts/Star - Pusher Game/Images/Background/boy.png
  PyGamesScripts/Star - Pusher Game/Images/Background/catgirl.png
  PyGamesScripts/Star - Pusher Game/Images/Background/horngirl.png
  PyGamesScripts/Star - Pusher Game/Images/Background/pinkgirl.png
  PyGamesScripts/Star - Pusher Game/Images/Background/princess.png
  PyGamesScripts/Star - Pusher Game/Images/Background/star_solved.png
  PyGamesScripts/Star - Pusher Game/Images/Background/star_title.png
  PyGamesScripts/Star - Pusher Game/Images/Output/Image-1.png
  PyGamesScripts/Star - Pusher Game/Images/Output/Image-2.png
  PyGamesScripts/Star - Pusher Game/Level Template/starPusherLevels.txt
  PyGamesScripts/Star - Pusher Game/README.md
  PyGamesScripts/Star - Pusher Game/requirements.txt
  PyGamesScripts/Star - Pusher Game/star_pusher_game.py
Labels: LGMSOC21, To Do, 🟧 Level3

#759 Ideal Weight Calculator
  GUIScripts/Ideal Weight Calculator/Images/output1.JPG
  GUIScripts/Ideal Weight Calculator/Images/output2.JPG
  GUIScripts/Ideal Weight Calculator/Images/output3.JPG
  GUIScripts/Ideal Weight Calculator/Images/output4.JPG
  GUIScripts/Ideal Weight Calculator/README.md
  GUIScripts/Ideal Weight Calculator/ideal_weight.py
  GUIScripts/Ideal Weight Calculator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#762 Added Aadhaar Card Generation Application in GUIScripts
  GUIScripts/Aadhaar Card Generation Application/Images/1.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/2.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/3.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/4.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/5.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/6.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/7.jpg
  GUIScripts/Aadhaar Card Generation Application/Images/aadhaar_front.gif
  GUIScripts/Aadhaar Card Generation Application/Images/fourth_front.gif
  GUIScripts/Aadhaar Card Generation Application/Images/sec_front.gif
  GUIScripts/Aadhaar Card Generation Application/Images/third_front.gif
  GUIScripts/Aadhaar Card Generation Application/README.md
  GUIScripts/Aadhaar Card Generation Application/aadhaar_card_generation_application.py
  GUIScripts/Aadhaar Card Generation Application/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#752 Income Tax Calculator
  GUIScripts/Income Tax Calculator/Images/Screenshot (836).png
  GUIScripts/Income Tax Calculator/README.md
  GUIScripts/Income Tax Calculator/income_tax_calculator.py
  GUIScripts/Income Tax Calculator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#764 Reversegram - Game
  PyGamesScripts/Reversegram/Images/Image-1.png
  PyGamesScripts/Reversegram/README.md
  PyGamesScripts/Reversegram/requirements.txt
  PyGamesScripts/Reversegram/reversegram_game.py
Labels: LGMSOC21, To Do, 🟨 Level2

#767 Added Correct Flow Game in Pygame Scripts
  PyGamesScripts/Correct Flow Game/Images/1.gif
  PyGamesScripts/Correct Flow Game/Images/2.gif
  PyGamesScripts/Correct Flow Game/Images/3.gif
  PyGamesScripts/Correct Flow Game/Images/4.gif
  PyGamesScripts/Correct Flow Game/Images/5.gif
  PyGamesScripts/Correct Flow Game/Images/6.gif
  PyGamesScripts/Correct Flow Game/Images/7.gif
  PyGamesScripts/Correct Flow Game/Images/8.gif
  PyGamesScripts/Correct Flow Game/Images/front.gif
  PyGamesScripts/Correct Flow Game/Images/score2.gif
  PyGamesScripts/Correct Flow Game/README.md
  PyGamesScripts/Correct Flow Game/correct_flow_game.py
  PyGamesScripts/Correct Flow Game/data.json
  PyGamesScripts/Correct Flow Game/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#771 Added Detect The Language in GUIScripts
  GUIScripts/Detect The Language/Images/1.jpg
  GUIScripts/Detect The Language/Images/2.jpg
  GUIScripts/Detect The Language/Images/3.jpg
  GUIScripts/Detect The Language/Images/4.jpg
  GUIScripts/Detect The Language/Images/5.jpg
  GUIScripts/Detect The Language/Images/6.jpg
  GUIScripts/Detect The Language/Images/7.jpg
  GUIScripts/Detect The Language/Images/8.jpg
  GUIScripts/Detect The Language/Images/language.gif
  GUIScripts/Detect The Language/README.md
  GUIScripts/Detect The Language/detect_the_language.py
  GUIScripts/Detect The Language/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#768 Added Family Key Logger
  EthicalHackingScripts/Family Key Logger/Images/Screenshot (368).png
  EthicalHackingScripts/Family Key Logger/README.md
  EthicalHackingScripts/Family Key Logger/Related files/key_icon.ico
  EthicalHackingScripts/Family Key Logger/key_logger.py
  EthicalHackingScripts/Family Key Logger/requirements.txt
  EthicalHackingScripts/README.md
  README.md
Labels: DCP21, 🟩 Level1

#779 PDF Merger
  BasicPythonScripts/PDF Merger/Images/output(pdf_merge).png
  BasicPythonScripts/PDF Merger/README.md
  BasicPythonScripts/PDF Merger/new.pdf
  BasicPythonScripts/PDF Merger/pdf_merger.py
  BasicPythonScripts/PDF Merger/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#778 Added Image Encryption Decryption in ImageProcessing Scripts
  ImageProcessingScripts/Image Encryption Decryption/Images/1.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/10.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/11.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/2.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/3.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/4.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/5.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/6.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/7.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/8.jpg
  ImageProcessingScripts/Image Encryption Decryption/Images/9.jpg
  ImageProcessingScripts/Image Encryption Decryption/README.md
  ImageProcessingScripts/Image Encryption Decryption/image_encryption_decryption.py
  ImageProcessingScripts/Image Encryption Decryption/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#776 Dodger
  GUIScripts/Dodger/Images/Dodger 2021-07-16 17-42-29.mp4
  GUIScripts/Dodger/Images/Image-1.png
  GUIScripts/Dodger/Images/Image-2.png
  GUIScripts/Dodger/README.md
  GUIScripts/Dodger/dodger.py
  GUIScripts/Dodger/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#785 Added Video Stitching in GUIScripts
  GUIScripts/Video Stitching/Images/1.jpg
  GUIScripts/Video Stitching/Images/10.jpg
  GUIScripts/Video Stitching/Images/11.jpg
  GUIScripts/Video Stitching/Images/2.jpg
  GUIScripts/Video Stitching/Images/3.jpg
  GUIScripts/Video Stitching/Images/4.jpg
  GUIScripts/Video Stitching/Images/5.jpg
  GUIScripts/Video Stitching/Images/6.jpg
  GUIScripts/Video Stitching/Images/7.jpg
  GUIScripts/Video Stitching/Images/8.jpg
  GUIScripts/Video Stitching/Images/9.jpg
  GUIScripts/Video Stitching/Images/vid_stitch.jpg
  GUIScripts/Video Stitching/README.md
  GUIScripts/Video Stitching/requirements.txt
  GUIScripts/Video Stitching/video_stitching.py
Labels: Assigned, To Do, 🟧 Level3

#787 Avatar Creator
  BasicPythonScripts/Avatar Creator/Images/Output_2(avataar).png
  BasicPythonScripts/Avatar Creator/Images/output_1(avatar).png
  BasicPythonScripts/Avatar Creator/README.md
  BasicPythonScripts/Avatar Creator/avatar_creator.py
  BasicPythonScripts/Avatar Creator/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#790 Added Image Snipper in ImageProcessing Scripts
  ImageProcessingScripts/Image Snipper/Images/1.jpg
  ImageProcessingScripts/Image Snipper/Images/2.jpg
  ImageProcessingScripts/Image Snipper/Images/3.jpg
  ImageProcessingScripts/Image Snipper/Images/4.jpg
  ImageProcessingScripts/Image Snipper/Images/5.jpg
  ImageProcessingScripts/Image Snipper/Images/6.jpg
  ImageProcessingScripts/Image Snipper/Images/7.jpg
  ImageProcessingScripts/Image Snipper/Images/front.jpg
  ImageProcessingScripts/Image Snipper/Images/second.jpg
  ImageProcessingScripts/Image Snipper/README.md
  ImageProcessingScripts/Image Snipper/image_snipper.py
  ImageProcessingScripts/Image Snipper/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#794 Added Image Watermark Remover in ImageProcessing Scripts
  ImageProcessingScripts/Image Watermark Remover/Images/1.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/2.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/3.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/4.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/5.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/6.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/front.jpg
  ImageProcessingScripts/Image Watermark Remover/Images/second.jpg
  ImageProcessingScripts/Image Watermark Remover/README.md
  ImageProcessingScripts/Image Watermark Remover/image_watermark_remover.py
  ImageProcessingScripts/Image Watermark Remover/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#801 Added new anagram string script
  BasicPythonScripts/Anagram String/Images/Code_Output.png
  BasicPythonScripts/Anagram String/Images/anagram_code.PNG
  BasicPythonScripts/Anagram String/README.md
  BasicPythonScripts/Anagram String/anagram_string.py
  BasicPythonScripts/Anagram String/requirements.txt
Labels: DCP21, 🟪 Level0

#797 Enhanced English Dictionary with Text to Speech Feature
  GUIScripts/English Dictionary/Images/1.jpg
  GUIScripts/English Dictionary/Images/1.png
  GUIScripts/English Dictionary/Images/2.jpg
  GUIScripts/English Dictionary/Images/2.png
  GUIScripts/English Dictionary/Images/3.jpg
  GUIScripts/English Dictionary/Images/3.png
  GUIScripts/English Dictionary/Images/4.jpg
  GUIScripts/English Dictionary/Images/4.png
  GUIScripts/English Dictionary/Images/5.jpg
  GUIScripts/English Dictionary/Images/5.png
  GUIScripts/English Dictionary/Images/6.jpg
  GUIScripts/English Dictionary/Images/6.png
  GUIScripts/English Dictionary/Images/7.jpg
  GUIScripts/English Dictionary/Images/7.png
  GUIScripts/English Dictionary/Images/8.jpg
  GUIScripts/English Dictionary/Images/8.png
  GUIScripts/English Dictionary/README_enhanced.md
  GUIScripts/English Dictionary/english_dictionary.py
  GUIScripts/English Dictionary/requirements.txt
Labels: LGMSOC21, To Do, enhancement, 🟩 Level1

#802 Spotify Song Lyrics Extractor
  WebScrapingScripts/Spotify Song Lyrics Extractor/Images/output1.png
  WebScrapingScripts/Spotify Song Lyrics Extractor/Images/output2.png
  WebScrapingScripts/Spotify Song Lyrics Extractor/Images/output3.png
  WebScrapingScripts/Spotify Song Lyrics Extractor/README.md
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/API_Credentials.json
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Alessia Cara - Scars To Your Beautiful.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Anson Seabra - Walked Through Hell.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Ashe, Niall Horan - Moral of the Story (feat. Niall Horan).txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Ava Max - Kings & Queens.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Bebe Rexha - I'm a Mess.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Camila Cabello - Crying in the Club.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Camila Cabello - Liar.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Camila Cabello, Quavo - OMG (feat. Quavo).txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Conan Gray - Heather.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/DNCE - Cake By The Ocean.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Demi Lovato - Heart Attack.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Duncan Laurence, FLETCHER - Arcade (feat. FLETCHER).txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/FLETCHER, Kito, Trevor Daniel - Bitter (feat. Trevor Daniel).txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Harry Styles - Adore You.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Jonas Brothers - What A Man Gotta Do.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Neena Rose - War Zone.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Noah Cyrus - July.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Olivia Rodrigo - drivers license.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Selena Gomez, Gucci Mane - Fetish (feat. Gucci Mane).txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Tate McRae - you broke me first.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/The Kid LAROI - WITHOUT YOU.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Twan Ray - Hello She Said Goodbye.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Twan Ray - We Could Start a Thing.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/Zara Larsson - Lush Life.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/before you go.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/Related/Lyrics/salem ilese - Mad at Disney.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/requirements.txt
  WebScrapingScripts/Spotify Song Lyrics Extractor/spotify_song_lyrics_extractor.py
Labels: DCP21, To Do, 🟨 Level2

#803 Added HTTP Error Code in Codes in GUIScripts
  GUIScripts/HTTP Error Codes/Images/1.jpg
  GUIScripts/HTTP Error Codes/Images/2.jpg
  GUIScripts/HTTP Error Codes/Images/3.jpg
  GUIScripts/HTTP Error Codes/Images/4.jpg
  GUIScripts/HTTP Error Codes/Images/5.jpg
  GUIScripts/HTTP Error Codes/Images/6.jpg
  GUIScripts/HTTP Error Codes/Images/7.jpg
  GUIScripts/HTTP Error Codes/Images/8.jpg
  GUIScripts/HTTP Error Codes/Images/front.gif
  GUIScripts/HTTP Error Codes/Images/second.gif
  GUIScripts/HTTP Error Codes/README.md
  GUIScripts/HTTP Error Codes/code_data.json
  GUIScripts/HTTP Error Codes/http_error_code.py
  GUIScripts/HTTP Error Codes/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#796 Quotes Extractor
  WebScrapingScripts/Quotes Extractor/Images/Authors.png
  WebScrapingScripts/Quotes Extractor/Images/DataFrame.png
  WebScrapingScripts/Quotes Extractor/Images/Quotes.png
  WebScrapingScripts/Quotes Extractor/Quotes.csv
  WebScrapingScripts/Quotes Extractor/README.md
  WebScrapingScripts/Quotes Extractor/quotes_extractor.py
  WebScrapingScripts/Quotes Extractor/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#788 created Image Steganography(CMD)
  BasicPythonScripts/Image Steganography/Images/img.jpeg
  BasicPythonScripts/Image Steganography/Images/module.PNG
  BasicPythonScripts/Image Steganography/Images/output.png
  BasicPythonScripts/Image Steganography/Images/output1.png
  BasicPythonScripts/Image Steganography/Images/test.PNG
  BasicPythonScripts/Image Steganography/README.md
  BasicPythonScripts/Image Steganography/image_steganography.py
  BasicPythonScripts/Image Steganography/requirements.txt
Labels: DCP21, To Do, 🟩 Level1

#812 Added Yandex Website Clone in GUIScripts
  GUIScripts/Yandex Website Clone/Images/1.jpg
  GUIScripts/Yandex Website Clone/Images/10.jpg
  GUIScripts/Yandex Website Clone/Images/2.jpg
  GUIScripts/Yandex Website Clone/Images/3.jpg
  GUIScripts/Yandex Website Clone/Images/4.jpg
  GUIScripts/Yandex Website Clone/Images/5.jpg
  GUIScripts/Yandex Website Clone/Images/6.jpg
  GUIScripts/Yandex Website Clone/Images/7.jpg
  GUIScripts/Yandex Website Clone/Images/8.jpg
  GUIScripts/Yandex Website Clone/Images/front.jpg
  GUIScripts/Yandex Website Clone/Images/yandex.jpg
  GUIScripts/Yandex Website Clone/Images/yandex_icon.ico
  GUIScripts/Yandex Website Clone/README.md
  GUIScripts/Yandex Website Clone/requirements.txt
  GUIScripts/Yandex Website Clone/yandex_website_clone.py
Labels: LGMSOC21, To Do, 🟥 Level4

#810 Image Size Compressor
  ImageProcessingScripts/Image Size Compressor/Images/output_1(img_compressor).png
  ImageProcessingScripts/Image Size Compressor/Images/output_2(img_compressor).png
  ImageProcessingScripts/Image Size Compressor/README.md
  ImageProcessingScripts/Image Size Compressor/image_size_compressor.py
  ImageProcessingScripts/Image Size Compressor/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#811 GUI based YouTube Video Downloader
  GUIScripts/Youtube Video Downloader/Images/after_download.png
  GUIScripts/Youtube Video Downloader/Images/before_download.png
  GUIScripts/Youtube Video Downloader/Images/before_link.png
  GUIScripts/Youtube Video Downloader/README.MD
  GUIScripts/Youtube Video Downloader/requirements.txt
  GUIScripts/Youtube Video Downloader/youtube_video_downloader.py
Labels: LGMSOC21, To Do, 🟩 Level1

#816 Added Mouse Speed Tracker in GUIScripts
  GUIScripts/Mouse Speed Tracker/Images/1.jpg
  GUIScripts/Mouse Speed Tracker/Images/2.jpg
  GUIScripts/Mouse Speed Tracker/Images/3.jpg
  GUIScripts/Mouse Speed Tracker/Images/4.jpg
  GUIScripts/Mouse Speed Tracker/Images/5.jpg
  GUIScripts/Mouse Speed Tracker/Images/6.jpg
  GUIScripts/Mouse Speed Tracker/README.md
  GUIScripts/Mouse Speed Tracker/mouse_speed_tracker.py
  GUIScripts/Mouse Speed Tracker/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#818 Enhanced Speech input in English Dictionary in GUIScripts
  GUIScripts/English Dictionary/Images/1.jpg
  GUIScripts/English Dictionary/Images/2.jpg
  GUIScripts/English Dictionary/Images/3.jpg
  GUIScripts/English Dictionary/Images/4.jpg
  GUIScripts/English Dictionary/Images/5.jpg
  GUIScripts/English Dictionary/Images/6.jpg
  GUIScripts/English Dictionary/Images/7.jpg
  GUIScripts/English Dictionary/Images/8.jpg
  GUIScripts/English Dictionary/README_enhanced.md
  GUIScripts/English Dictionary/english_dictionary.py
  GUIScripts/English Dictionary/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#819 The 2D Shape Area Calculator
  BasicPythonScripts/The 2D Shape Area Calculator/2D_shapes_area_calculator.py
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfCircle.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfEllipse.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfParallelogram.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfRectangle.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfSquare.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfTrapezium.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfTriangle1.png
  BasicPythonScripts/The 2D Shape Area Calculator/Images/AreaOfTriangle2.png
  BasicPythonScripts/The 2D Shape Area Calculator/README.md
  BasicPythonScripts/The 2D Shape Area Calculator/requirements.txt
Labels: DCP21, To Do, 🟩 Level1

#821 Added Text to Captcha Image in GUIScripts
  GUIScripts/Text to Captcha Image/Images/1.jpg
  GUIScripts/Text to Captcha Image/Images/2.jpg
  GUIScripts/Text to Captcha Image/Images/3.jpg
  GUIScripts/Text to Captcha Image/Images/4.jpg
  GUIScripts/Text to Captcha Image/Images/5.jpg
  GUIScripts/Text to Captcha Image/Images/6.jpg
  GUIScripts/Text to Captcha Image/Images/7.jpg
  GUIScripts/Text to Captcha Image/Images/original.jpg
  GUIScripts/Text to Captcha Image/README.md
  GUIScripts/Text to Captcha Image/requirements.txt
  GUIScripts/Text to Captcha Image/text_to_captcha_image.py
Labels: LGMSOC21, To Do, 🟨 Level2

#824 Added Text On Image in GUIScripts
  GUIScripts/Text On Image/Images/1.jpg
  GUIScripts/Text On Image/Images/10.jpg
  GUIScripts/Text On Image/Images/11.jpg
  GUIScripts/Text On Image/Images/12.jpg
  GUIScripts/Text On Image/Images/2.jpg
  GUIScripts/Text On Image/Images/3.jpg
  GUIScripts/Text On Image/Images/4.jpg
  GUIScripts/Text On Image/Images/5.jpg
  GUIScripts/Text On Image/Images/6.jpg
  GUIScripts/Text On Image/Images/7.jpg
  GUIScripts/Text On Image/Images/8.jpg
  GUIScripts/Text On Image/Images/9.jpg
  GUIScripts/Text On Image/README.md
  GUIScripts/Text On Image/requirements.txt
  GUIScripts/Text On Image/text_on_image.py
Labels: LGMSOC21, To Do, 🟨 Level2

#831 Added Video Property Fetcher in GUIScripts
  GUIScripts/Video Property Fetcher/Images/1.jpg
  GUIScripts/Video Property Fetcher/Images/10.jpg
  GUIScripts/Video Property Fetcher/Images/2.jpg
  GUIScripts/Video Property Fetcher/Images/3.jpg
  GUIScripts/Video Property Fetcher/Images/4.jpg
  GUIScripts/Video Property Fetcher/Images/5.jpg
  GUIScripts/Video Property Fetcher/Images/6.jpg
  GUIScripts/Video Property Fetcher/Images/7.jpg
  GUIScripts/Video Property Fetcher/Images/8.jpg
  GUIScripts/Video Property Fetcher/Images/9.jpg
  GUIScripts/Video Property Fetcher/Images/front.jpg
  GUIScripts/Video Property Fetcher/README.md
  GUIScripts/Video Property Fetcher/requirements.txt
  GUIScripts/Video Property Fetcher/video_property_fetcher.py
Labels: LGMSOC21, To Do, 🟨 Level2

#827 Added Video to Images in GUIScripts
  GUIScripts/Video to Images/Images/1.jpg
  GUIScripts/Video to Images/Images/10.jpg
  GUIScripts/Video to Images/Images/2.jpg
  GUIScripts/Video to Images/Images/3.jpg
  GUIScripts/Video to Images/Images/4.jpg
  GUIScripts/Video to Images/Images/5.jpg
  GUIScripts/Video to Images/Images/6.jpg
  GUIScripts/Video to Images/Images/7.jpg
  GUIScripts/Video to Images/Images/8.jpg
  GUIScripts/Video to Images/Images/9.jpg
  GUIScripts/Video to Images/Images/front.jpg
  GUIScripts/Video to Images/README.md
  GUIScripts/Video to Images/requirements.txt
  GUIScripts/Video to Images/video_to_images.py
Labels: LGMSOC21, To Do, 🟨 Level2

#833 Added Emoji Dictionary in GUIScripts
  GUIScripts/Emoji Dictionary/Images/1.jpg
  GUIScripts/Emoji Dictionary/Images/2.jpg
  GUIScripts/Emoji Dictionary/Images/3.jpg
  GUIScripts/Emoji Dictionary/Images/4.jpg
  GUIScripts/Emoji Dictionary/Images/5.jpg
  GUIScripts/Emoji Dictionary/Images/6.jpg
  GUIScripts/Emoji Dictionary/Images/7.jpg
  GUIScripts/Emoji Dictionary/Images/8.jpg
  GUIScripts/Emoji Dictionary/Images/9.jpg
  GUIScripts/Emoji Dictionary/README.md
  GUIScripts/Emoji Dictionary/emoji_dictionary.py
  GUIScripts/Emoji Dictionary/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#839 Telegram Bot
  AutomationScripts/Telegram Bot/Images/output(telegram_bot).png
  AutomationScripts/Telegram Bot/README.md
  AutomationScripts/Telegram Bot/requirements.txt
  AutomationScripts/Telegram Bot/telegram_bot.py
Labels: LGMSOC21, To Do, 🟩 Level1

#838 Added Video Cropper in GUIScripts
  GUIScripts/Video Cropper/Images/1.jpg
  GUIScripts/Video Cropper/Images/2.jpg
  GUIScripts/Video Cropper/Images/3.jpg
  GUIScripts/Video Cropper/Images/4.jpg
  GUIScripts/Video Cropper/Images/5.jpg
  GUIScripts/Video Cropper/Images/6.jpg
  GUIScripts/Video Cropper/Images/7.jpg
  GUIScripts/Video Cropper/Images/8.jpg
  GUIScripts/Video Cropper/Images/9.jpg
  GUIScripts/Video Cropper/Images/front.jpg
  GUIScripts/Video Cropper/README.md
  GUIScripts/Video Cropper/requirements.txt
  GUIScripts/Video Cropper/video_cropper.py
Labels: LGMSOC21, To Do, 🟨 Level2

#836 Enhanced snake game
  PyGamesScripts/Snake Game/Enhanced/Images/output.png
  PyGamesScripts/Snake Game/Enhanced/README.md
  PyGamesScripts/Snake Game/Enhanced/food.py
  PyGamesScripts/Snake Game/Enhanced/high_score.txt
  PyGamesScripts/Snake Game/Enhanced/main.py
  PyGamesScripts/Snake Game/Enhanced/requirements.txt
  PyGamesScripts/Snake Game/Enhanced/scoreboard.py
  PyGamesScripts/Snake Game/Enhanced/snake.py
Labels: DCP21, To Do, enhancement, 🟨 Level2

#814 Billing System GUI
  GUIScripts/Billing System/Images/Bill.PNG
  GUIScripts/Billing System/Images/Output.PNG
  GUIScripts/Billing System/README.md
  GUIScripts/Billing System/billing_system.py
  GUIScripts/Billing System/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#841 Added Image Noise Remover in ImageProcessing Scripts
  ImageProcessingScripts/Image Noise Remover/Images/1.jpg
  ImageProcessingScripts/Image Noise Remover/Images/10.jpg
  ImageProcessingScripts/Image Noise Remover/Images/2.jpg
  ImageProcessingScripts/Image Noise Remover/Images/3.jpg
  ImageProcessingScripts/Image Noise Remover/Images/4.jpg
  ImageProcessingScripts/Image Noise Remover/Images/5.jpg
  ImageProcessingScripts/Image Noise Remover/Images/6.jpg
  ImageProcessingScripts/Image Noise Remover/Images/7.jpg
  ImageProcessingScripts/Image Noise Remover/Images/8.jpg
  ImageProcessingScripts/Image Noise Remover/Images/9.jpg
  ImageProcessingScripts/Image Noise Remover/README.md
  ImageProcessingScripts/Image Noise Remover/image_noise_remover.py
  ImageProcessingScripts/Image Noise Remover/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#823 MOVIE REVIEWS SCRAPING
  WebScrapingScripts/Movie Review Scraping/.ipynb_checkpoints/IMBD DATA SCRAPING-checkpoint.ipynb
  WebScrapingScripts/Movie Review Scraping/Images/img.png
  WebScrapingScripts/Movie Review Scraping/Images/terminal.png
  WebScrapingScripts/Movie Review Scraping/README.md
  WebScrapingScripts/Movie Review Scraping/img.png
  WebScrapingScripts/Movie Review Scraping/requirements.txt
  WebScrapingScripts/Movie Review Scraping/scrap_data.py
  WebScrapingScripts/Movie Review Scraping/terminal.png
Labels: DCP21, To Do, 🟨 Level2

#845 Added Color Mixer in GUIScripts
  GUIScripts/Color Mixer/Images/1.jpg
  GUIScripts/Color Mixer/Images/10.jpg
  GUIScripts/Color Mixer/Images/11.jpg
  GUIScripts/Color Mixer/Images/2.jpg
  GUIScripts/Color Mixer/Images/3.jpg
  GUIScripts/Color Mixer/Images/4.jpg
  GUIScripts/Color Mixer/Images/5.jpg
  GUIScripts/Color Mixer/Images/6.jpg
  GUIScripts/Color Mixer/Images/7.jpg
  GUIScripts/Color Mixer/Images/8.jpg
  GUIScripts/Color Mixer/Images/9.jpg
  GUIScripts/Color Mixer/Images/front.jpg
  GUIScripts/Color Mixer/Images/second.png
  GUIScripts/Color Mixer/README.md
  GUIScripts/Color Mixer/color_mixer.py
  GUIScripts/Color Mixer/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#847 Added Unicode and Emoji in GUIScripts
  GUIScripts/Unicode and Emoji/Images/1.jpg
  GUIScripts/Unicode and Emoji/Images/2.jpg
  GUIScripts/Unicode and Emoji/Images/3.jpg
  GUIScripts/Unicode and Emoji/Images/4.jpg
  GUIScripts/Unicode and Emoji/Images/5.jpg
  GUIScripts/Unicode and Emoji/Images/6.jpg
  GUIScripts/Unicode and Emoji/Images/front.jpg
  GUIScripts/Unicode and Emoji/Images/second.jpg
  GUIScripts/Unicode and Emoji/README.md
  GUIScripts/Unicode and Emoji/emoji_df.csv
  GUIScripts/Unicode and Emoji/requirements.txt
  GUIScripts/Unicode and Emoji/unicode_and_emoji.py
Labels: LGMSOC21, To Do, 🟧 Level3

#844 Covid CasesAPI
  APIScripts/Covid CasesAPI/Images/covid.png
  APIScripts/Covid CasesAPI/README.md
  APIScripts/Covid CasesAPI/covid_updates.py
  APIScripts/Covid CasesAPI/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#849 Added Image Segmentation in ImageProcessing Scripts
  ImageProcessingScripts/Image Segmentation/Images/1.jpg
  ImageProcessingScripts/Image Segmentation/Images/10.jpg
  ImageProcessingScripts/Image Segmentation/Images/11.jpg
  ImageProcessingScripts/Image Segmentation/Images/12.jpg
  ImageProcessingScripts/Image Segmentation/Images/2.jpg
  ImageProcessingScripts/Image Segmentation/Images/3.jpg
  ImageProcessingScripts/Image Segmentation/Images/4.jpg
  ImageProcessingScripts/Image Segmentation/Images/5.jpg
  ImageProcessingScripts/Image Segmentation/Images/6.jpg
  ImageProcessingScripts/Image Segmentation/Images/7.jpg
  ImageProcessingScripts/Image Segmentation/Images/8.jpg
  ImageProcessingScripts/Image Segmentation/Images/9.jpg
  ImageProcessingScripts/Image Segmentation/Images/front.jpg
  ImageProcessingScripts/Image Segmentation/README.md
  ImageProcessingScripts/Image Segmentation/image_segmentation.py
  ImageProcessingScripts/Image Segmentation/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#837 Python based GUI to encrypt and decrypt text
  GUIScripts/Text Encryption and Decryption/Images/Screenshot (338).png
  GUIScripts/Text Encryption and Decryption/Images/Screenshot (339).png
  GUIScripts/Text Encryption and Decryption/Images/Screenshot (340).png
  GUIScripts/Text Encryption and Decryption/Images/Screenshot (341).png
  GUIScripts/Text Encryption and Decryption/Images/Screenshot (342).png
  GUIScripts/Text Encryption and Decryption/README.md
  GUIScripts/Text Encryption and Decryption/requirements.txt
  GUIScripts/Text Encryption and Decryption/text_encryption_and_decryption.py
Labels: DCP21, To Do, 🟨 Level2

#852 Added Map Coloring in ImageProcessing Scripts
  ImageProcessingScripts/Map Coloring/Images/1.jpg
  ImageProcessingScripts/Map Coloring/Images/10.jpg
  ImageProcessingScripts/Map Coloring/Images/11.jpg
  ImageProcessingScripts/Map Coloring/Images/12.jpg
  ImageProcessingScripts/Map Coloring/Images/2.jpg
  ImageProcessingScripts/Map Coloring/Images/3.jpg
  ImageProcessingScripts/Map Coloring/Images/4.jpg
  ImageProcessingScripts/Map Coloring/Images/5.jpg
  ImageProcessingScripts/Map Coloring/Images/6.jpg
  ImageProcessingScripts/Map Coloring/Images/7.jpg
  ImageProcessingScripts/Map Coloring/Images/8.jpg
  ImageProcessingScripts/Map Coloring/Images/9.jpg
  ImageProcessingScripts/Map Coloring/Images/front.jpg
  ImageProcessingScripts/Map Coloring/README.md
  ImageProcessingScripts/Map Coloring/map_coloring.py
  ImageProcessingScripts/Map Coloring/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#853 Pokedex GUI
  GUIScripts/Pokedex GUI/Images/output_1(pokedex).png
  GUIScripts/Pokedex GUI/Images/output_2(pokedex).png
  GUIScripts/Pokedex GUI/Images/output_3(pokedex).png
  GUIScripts/Pokedex GUI/Images/output_4(pokedex).png
  GUIScripts/Pokedex GUI/README.md
  GUIScripts/Pokedex GUI/pokedex_gui.py
  GUIScripts/Pokedex GUI/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#857 Added Decode Image Game in Pygames Scripts
  PyGamesScripts/Decode Image Game/Images/1.jpg
  PyGamesScripts/Decode Image Game/Images/10.jpg
  PyGamesScripts/Decode Image Game/Images/11.jpg
  PyGamesScripts/Decode Image Game/Images/2.jpg
  PyGamesScripts/Decode Image Game/Images/3.jpg
  PyGamesScripts/Decode Image Game/Images/4.jpg
  PyGamesScripts/Decode Image Game/Images/5.jpg
  PyGamesScripts/Decode Image Game/Images/6.jpg
  PyGamesScripts/Decode Image Game/Images/7.jpg
  PyGamesScripts/Decode Image Game/Images/8.jpg
  PyGamesScripts/Decode Image Game/Images/9.jpg
  PyGamesScripts/Decode Image Game/Images/front.jpg
  PyGamesScripts/Decode Image Game/Images/img1.gif
  PyGamesScripts/Decode Image Game/Images/img2.gif
  PyGamesScripts/Decode Image Game/Images/img3.gif
  PyGamesScripts/Decode Image Game/Images/img4.gif
  PyGamesScripts/Decode Image Game/Images/img5.gif
  PyGamesScripts/Decode Image Game/Images/img6.gif
  PyGamesScripts/Decode Image Game/Images/img7.gif
  PyGamesScripts/Decode Image Game/Images/img8.gif
  PyGamesScripts/Decode Image Game/README.md
  PyGamesScripts/Decode Image Game/decode_image _game.py
  PyGamesScripts/Decode Image Game/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#860 Added Object Counter in Image in ImageProcessing Scripts
  ImageProcessingScripts/Object Counter in Image/Images/1.jpg
  ImageProcessingScripts/Object Counter in Image/Images/10.jpg
  ImageProcessingScripts/Object Counter in Image/Images/2.jpg
  ImageProcessingScripts/Object Counter in Image/Images/3.jpg
  ImageProcessingScripts/Object Counter in Image/Images/4.jpg
  ImageProcessingScripts/Object Counter in Image/Images/5.jpg
  ImageProcessingScripts/Object Counter in Image/Images/6.jpg
  ImageProcessingScripts/Object Counter in Image/Images/7.jpg
  ImageProcessingScripts/Object Counter in Image/Images/8.jpg
  ImageProcessingScripts/Object Counter in Image/Images/9.jpg
  ImageProcessingScripts/Object Counter in Image/Images/front.jpg
  ImageProcessingScripts/Object Counter in Image/README.md
  ImageProcessingScripts/Object Counter in Image/object_counter_in_image.py
  ImageProcessingScripts/Object Counter in Image/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#863 Zip File Creator
  BasicPythonScripts/Zip File Creator/Images/output(zip_creator).png
  BasicPythonScripts/Zip File Creator/README.md
  BasicPythonScripts/Zip File Creator/requirements.txt
  BasicPythonScripts/Zip File Creator/zip_file_creator.py
Labels: LGMSOC21, To Do, 🟩 Level1

#864 Added Images Slideshow in ImageProcessing Scripts
  ImageProcessingScripts/Images Slideshow/Images/1.jpg
  ImageProcessingScripts/Images Slideshow/Images/10.jpg
  ImageProcessingScripts/Images Slideshow/Images/2.jpg
  ImageProcessingScripts/Images Slideshow/Images/3.jpg
  ImageProcessingScripts/Images Slideshow/Images/4.jpg
  ImageProcessingScripts/Images Slideshow/Images/5.jpg
  ImageProcessingScripts/Images Slideshow/Images/6.jpg
  ImageProcessingScripts/Images Slideshow/Images/7.jpg
  ImageProcessingScripts/Images Slideshow/Images/8.jpg
  ImageProcessingScripts/Images Slideshow/Images/9.jpg
  ImageProcessingScripts/Images Slideshow/Images/front.jpg
  ImageProcessingScripts/Images Slideshow/Images/second.png
  ImageProcessingScripts/Images Slideshow/README.md
  ImageProcessingScripts/Images Slideshow/images_slideshow.py
  ImageProcessingScripts/Images Slideshow/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#869 Added Text Summarizer in GUIScripts
  GUIScripts/Text Summarizer/Images/1.jpg
  GUIScripts/Text Summarizer/Images/2.jpg
  GUIScripts/Text Summarizer/Images/3.jpg
  GUIScripts/Text Summarizer/Images/4.jpg
  GUIScripts/Text Summarizer/Images/5.jpg
  GUIScripts/Text Summarizer/Images/6.jpg
  GUIScripts/Text Summarizer/Images/7.jpg
  GUIScripts/Text Summarizer/Images/8.jpg
  GUIScripts/Text Summarizer/Images/9.jpg
  GUIScripts/Text Summarizer/Images/front.jpg
  GUIScripts/Text Summarizer/README.md
  GUIScripts/Text Summarizer/requirements.txt
  GUIScripts/Text Summarizer/text_summarizer.py
Labels: LGMSOC21, To Do, 🟨 Level2

#866 Enhanced Color Converter with RGB to LAB Conversion
  GUIScripts/Color Converter/Images/1.jpg
  GUIScripts/Color Converter/Images/10.jpg
  GUIScripts/Color Converter/Images/11.jpg
  GUIScripts/Color Converter/Images/12.jpg
  GUIScripts/Color Converter/Images/13.jpg
  GUIScripts/Color Converter/README_enhanced.md
  GUIScripts/Color Converter/color_converter.py
Labels: LGMSOC21, To Do, enhancement, 🟨 Level2

#873 Added Video to Grayscale in GUIScripts
  GUIScripts/Video to Grayscale/Images/1.jpg
  GUIScripts/Video to Grayscale/Images/2.jpg
  GUIScripts/Video to Grayscale/Images/3.jpg
  GUIScripts/Video to Grayscale/Images/4.jpg
  GUIScripts/Video to Grayscale/Images/5.jpg
  GUIScripts/Video to Grayscale/Images/6.jpg
  GUIScripts/Video to Grayscale/Images/7.jpg
  GUIScripts/Video to Grayscale/Images/8.jpg
  GUIScripts/Video to Grayscale/Images/9.jpg
  GUIScripts/Video to Grayscale/Images/front.png
  GUIScripts/Video to Grayscale/README.md
  GUIScripts/Video to Grayscale/requirements.txt
  GUIScripts/Video to Grayscale/video_to_grayscale.py
Labels: LGMSOC21, To Do, 🟨 Level2

#876 Added Image Contours Co-ordinates in ImageProcessing Scripts
  ImageProcessingScripts/Image Contours Co-ordinates/Images/1.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/10.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/11.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/12.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/13.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/2.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/3.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/4.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/5.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/6.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/7.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/8.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/9.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/Images/front.jpg
  ImageProcessingScripts/Image Contours Co-ordinates/README.md
  ImageProcessingScripts/Image Contours Co-ordinates/image_contours_co-ordinates.py
  ImageProcessingScripts/Image Contours Co-ordinates/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#879 Folder Content Sorter
  BasicPythonScripts/Folder Content Sorter/Images/after_running(folder_content_sorter).png
  BasicPythonScripts/Folder Content Sorter/Images/before_running(folder_content_sorter).png
  BasicPythonScripts/Folder Content Sorter/Images/output(folder_content_sorter).png
  BasicPythonScripts/Folder Content Sorter/README.md
  BasicPythonScripts/Folder Content Sorter/folder_content_sorter.py
  BasicPythonScripts/Folder Content Sorter/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#880 Added RGB Color Palette in GUIScripts
  GUIScripts/RGB Color Palette/Images/1.jpg
  GUIScripts/RGB Color Palette/Images/2.jpg
  GUIScripts/RGB Color Palette/Images/3.jpg
  GUIScripts/RGB Color Palette/Images/4.jpg
  GUIScripts/RGB Color Palette/Images/5.jpg
  GUIScripts/RGB Color Palette/Images/6.jpg
  GUIScripts/RGB Color Palette/Images/7.jpg
  GUIScripts/RGB Color Palette/Images/front.png
  GUIScripts/RGB Color Palette/README.md
  GUIScripts/RGB Color Palette/RGB_color_palette.py
  GUIScripts/RGB Color Palette/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#878 Added new Peterson Number Script
  BasicPythonScripts/Peterson Number/Images/Output.PNG
  BasicPythonScripts/Peterson Number/Images/code.PNG
  BasicPythonScripts/Peterson Number/README.md
  BasicPythonScripts/Peterson Number/peterson_number.py
  BasicPythonScripts/Peterson Number/requirements.txt
Labels: DCP21, To Do, 🟩 Level1

#883 Added Video Encryption Decryption in GUIScripts
  GUIScripts/Video Encryption Decryption/Images/1.jpg
  GUIScripts/Video Encryption Decryption/Images/2.jpg
  GUIScripts/Video Encryption Decryption/Images/3.jpg
  GUIScripts/Video Encryption Decryption/Images/5.jpg
  GUIScripts/Video Encryption Decryption/Images/6.jpg
  GUIScripts/Video Encryption Decryption/Images/7.jpg
  GUIScripts/Video Encryption Decryption/Images/8.jpg
  GUIScripts/Video Encryption Decryption/Images/9.jpg
  GUIScripts/Video Encryption Decryption/Images/front.jpg
  GUIScripts/Video Encryption Decryption/Images/sample.jpg
  GUIScripts/Video Encryption Decryption/README.md
  GUIScripts/Video Encryption Decryption/requirements.txt
  GUIScripts/Video Encryption Decryption/video_encryption_decryption.py
Labels: LGMSOC21, To Do, 🟧 Level3

#885 Snowfall Filter On Image
  ImageProcessingScripts/Snowfall Filter On Image/Images/output(snowfall).mp4
  ImageProcessingScripts/Snowfall Filter On Image/Images/output_1(snowfall).png
  ImageProcessingScripts/Snowfall Filter On Image/README.md
  ImageProcessingScripts/Snowfall Filter On Image/requirements.txt
  ImageProcessingScripts/Snowfall Filter On Image/snowfall_filter_on_image.py
Labels: LGMSOC21, To Do, 🟨 Level2

#889 Added GUI Scroll-View in GUIScripts
  GUIScripts/GUI Scroll-View/Images/1.jpg
  GUIScripts/GUI Scroll-View/Images/2.jpg
  GUIScripts/GUI Scroll-View/Images/3.jpg
  GUIScripts/GUI Scroll-View/Images/4.jpg
  GUIScripts/GUI Scroll-View/Images/5.jpg
  GUIScripts/GUI Scroll-View/Images/6.jpg
  GUIScripts/GUI Scroll-View/Images/f1.jpg
  GUIScripts/GUI Scroll-View/Images/f2.jpg
  GUIScripts/GUI Scroll-View/Images/f3.jpg
  GUIScripts/GUI Scroll-View/Images/f4.jpg
  GUIScripts/GUI Scroll-View/Images/f5.jpg
  GUIScripts/GUI Scroll-View/Images/front.jpg
  GUIScripts/GUI Scroll-View/README.md
  GUIScripts/GUI Scroll-View/gui_scroll_view.py
  GUIScripts/GUI Scroll-View/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#886 Added Color Difference in GUIScripts
  GUIScripts/Color Difference/Images/1.jpg
  GUIScripts/Color Difference/Images/2.jpg
  GUIScripts/Color Difference/Images/3.jpg
  GUIScripts/Color Difference/Images/4.jpg
  GUIScripts/Color Difference/Images/5.jpg
  GUIScripts/Color Difference/Images/6.jpg
  GUIScripts/Color Difference/Images/7.jpg
  GUIScripts/Color Difference/Images/8.jpg
  GUIScripts/Color Difference/Images/9.jpg
  GUIScripts/Color Difference/Images/diff_cheatsheet.jpg
  GUIScripts/Color Difference/Images/front.jpg
  GUIScripts/Color Difference/README.md
  GUIScripts/Color Difference/color_difference.py
  GUIScripts/Color Difference/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#898 Bank Data Finder
  BasicPythonScripts/Bank Data Finder/Images/output(bank_data_finder).mp4
  BasicPythonScripts/Bank Data Finder/Images/output_1(bank_data_finder).png
  BasicPythonScripts/Bank Data Finder/README.md
  BasicPythonScripts/Bank Data Finder/bank_data_finder.py
  BasicPythonScripts/Bank Data Finder/requirements.txt
Labels: LGMSOC21, To Do, 🟩 Level1

#894 Added Image Search in GUIScripts
  GUIScripts/Image Search/Images/1.jpg
  GUIScripts/Image Search/Images/10.jpg
  GUIScripts/Image Search/Images/11.jpg
  GUIScripts/Image Search/Images/12.jpg
  GUIScripts/Image Search/Images/13.jpg
  GUIScripts/Image Search/Images/14.jpg
  GUIScripts/Image Search/Images/15.jpg
  GUIScripts/Image Search/Images/2.jpg
  GUIScripts/Image Search/Images/3.jpg
  GUIScripts/Image Search/Images/4.jpg
  GUIScripts/Image Search/Images/5.jpg
  GUIScripts/Image Search/Images/6.jpg
  GUIScripts/Image Search/Images/7.jpg
  GUIScripts/Image Search/Images/8.jpg
  GUIScripts/Image Search/Images/9.jpg
  GUIScripts/Image Search/Images/front.png
  GUIScripts/Image Search/README.md
  GUIScripts/Image Search/image_search.py
  GUIScripts/Image Search/requirements.txt
Labels: LGMSOC21, To Do, 🟨 Level2

#899 Added Circular Image Cropper in ImageProcessing Scripts
  ImageProcessingScripts/Circular Image Cropper/Images/1.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/10.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/11.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/12.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/2.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/3.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/4.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/5.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/6.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/7.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/8.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/9.jpg
  ImageProcessingScripts/Circular Image Cropper/Images/front.jpg
  ImageProcessingScripts/Circular Image Cropper/README.md
  ImageProcessingScripts/Circular Image Cropper/circular_image_cropper.py
  ImageProcessingScripts/Circular Image Cropper/requirements.txt
Labels: LGMSOC21, To Do, 🟧 Level3

#901 Screen Recorder
  GUIScripts/Screen Recorder/Images/screenrecorder_output.jpeg
  GUIScripts/Screen Recorder/README.md
  GUIScripts/Screen Recorder/requirements.txt
  GUIScripts/Screen Recorder/screen_recorder.py
Labels: DCP21, To Do, 🟩 Level1
